export const backendIssues = [
    {
        issues: 'https://api.github.com/repos/hyperledger/cacti/issues/2569',
        title: 'build(deps): persistently bump word-wrap from 1.2.3 to >=1.2.5',
        body: 'The robots [1] sent a pull request to force `word-wrap` to be the upgraded version\r\nbut it specified it through the lock file instead of the manifest.\r\n\r\nThis task is to finish that job by making sure that the manifest declares \r\ndependencies that are then no longer necessitating the inclusion of the vulnerable\r\n`word-wrap` version through transitive dependencies.\r\n\r\n[1] https://github.com/hyperledger/cacti/pull/2568\r\n\r\n`yarn why word-wrap -R` output: \r\n\r\n```sh\r\n\u251c\u2500 @hyperledger/cacti-weaver-besu-cli@workspace:weaver/samples/besu/besu-cli\r\n\u2502  \u2514\u2500 @hyperledger/cacti-weaver-sdk-besu@workspace:weaver/sdks/besu/node (via 2.0.0-alpha.1)\r\n\u2502\r\n\u251c\u2500 @hyperledger/cacti-weaver-driver-fabric@workspace:weaver/core/drivers/fabric-driver\r\n\u2502  \u2514\u2500 @hyperledger/cacti-weaver-sdk-fabric@workspace:weaver/sdks/fabric/interoperation-node-sdk (via 2.0.0-alpha.1)\r\n\u2502\r\n\u251c\u2500 @hyperledger/cacti-weaver-fabric-cli@workspace:weaver/samples/fabric/fabric-cli\r\n\u2502  \u251c\u2500 @hyperledger/cacti-weaver-sdk-fabric@workspace:weaver/sdks/fabric/interoperation-node-sdk (via 2.0.0-alpha.1)\r\n\u2502  \u251c\u2500 eslint@npm:7.32.0 (via npm:^7.3.1)\r\n\u2502  \u2502  \u2514\u2500 optionator@npm:0.9.1 (via npm:^0.9.1)\r\n\u2502  \u2502     \u2514\u2500 word-wrap@npm:1.2.3 (via npm:^1.2.3)\r\n\u2502  \u251c\u2500 jest@npm:24.9.0 (via npm:^24.1.0)\r\n\u2502  \u2502  \u2514\u2500 jest-cli@npm:24.9.0 (via npm:^24.9.0)\r\n\u2502  \u2502     \u251c\u2500 @jest/core@npm:24.9.0 (via npm:^24.9.0)\r\n\u2502  \u2502     \u2502  \u251c\u2500 @jest/reporters@npm:24.9.0 (via npm:^24.9.0)\r\n\u2502  \u2502     \u2502  \u2502  \u2514\u2500 jest-runtime@npm:24.9.0 (via npm:^24.9.0)\r\n\u2502  \u2502     \u2502  \u2502     \u2514\u2500 jest-config@npm:24.9.0 (via npm:^24.9.0)\r\n\u2502  \u2502     \u2502  \u2502        \u2514\u2500 jest-environment-jsdom@npm:24.9.0 (via npm:^24.9.0)\r\n\u2502  \u2502     \u2502  \u2502           \u2514\u2500 jsdom@npm:11.12.0 (via npm:^11.5.1)\r\n\u2502  \u2502     \u2502  \u2502              \u2514\u2500 escodegen@npm:1.14.3 (via npm:^1.9.1)\r\n\u2502  \u2502     \u2502  \u2502                 \u2514\u2500 optionator@npm:0.8.3 (via npm:^0.8.1)\r\n\u2502  \u2502     \u2502  \u2502                    \u2514\u2500 word-wrap@npm:1.2.3 (via npm:~1.2.3)\r\n\u2502  \u2502     \u2502  \u251c\u2500 jest-config@npm:24.9.0 (via npm:^24.9.0)\r\n\u2502  \u2502     \u2502  \u2514\u2500 jest-runtime@npm:24.9.0 (via npm:^24.9.0)\r\n\u2502  \u2502     \u2514\u2500 jest-config@npm:24.9.0 (via npm:^24.9.0)\r\n\u2502  \u2514\u2500 pkg@npm:4.5.1 [5f084] (via npm:^4.5.1 [5f084])\r\n\u2502     \u2514\u2500 escodegen@npm:1.14.3 (via npm:^1.14.1)\r\n\u2502\r\n\u251c\u2500 @hyperledger/cacti-weaver-iin-agent@workspace:weaver/core/identity-management/iin-agent\r\n\u2502  \u251c\u2500 @hyperledger/cacti-weaver-sdk-fabric@workspace:weaver/sdks/fabric/interoperation-node-sdk (via 2.0.0-alpha.1)\r\n\u2502  \u2514\u2500 rewire@npm:4.0.1 (via npm:^4.0.1)\r\n\u2502     \u2514\u2500 eslint@npm:4.19.1 (via npm:^4.19.1)\r\n\u2502        \u2514\u2500 optionator@npm:0.8.3 (via npm:^0.8.2)\r\n\u2502\r\n\u251c\u2500 @hyperledger/cacti-weaver-sdk-besu@workspace:weaver/sdks/besu/node\r\n\u2502\r\n\u251c\u2500 @hyperledger/cacti-weaver-sdk-fabric@workspace:weaver/sdks/fabric/interoperation-node-sdk\r\n\u2502\r\n\u251c\u2500 @hyperledger/cactus-cmd-api-server@workspace:packages/cactus-cmd-api-server\r\n\u2502  \u2514\u2500 artillery@npm:1.7.9 (via npm:1.7.9)\r\n\u2502     \u2514\u2500 jsonpath@npm:1.1.1 (via npm:^1.0.2)\r\n\u2502        \u2514\u2500 static-eval@npm:2.0.2 (via npm:2.0.2)\r\n\u2502           \u2514\u2500 escodegen@npm:1.14.3 (via npm:^1.8.1)\r\n\u2502\r\n\u251c\u2500 @hyperledger/cactus-example-carbon-accounting-backend@workspace:examples/cactus-example-carbon-accounting-backend\r\n\u2502  \u2514\u2500 @hyperledger/cactus-cmd-api-server@workspace:packages/cactus-cmd-api-server (via 2.0.0-alpha.1)\r\n\u2502\r\n\u251c\u2500 @hyperledger/cactus-example-electricity-trade@workspace:examples/cactus-example-electricity-trade\r\n\u2502  \u2514\u2500 eslint@npm:7.32.0 (via npm:7.32.0)\r\n\u2502\r\n\u251c\u2500 @hyperledger/cactus-example-supply-chain-backend@workspace:examples/cactus-example-supply-chain-backend\r\n\u2502  \u2514\u2500 @hyperledger/cactus-cmd-api-server@workspace:packages/cactus-cmd-api-server (via 2.0.0-alpha.1)\r\n\u2502\r\n\u251c\u2500 @hyperledger/cactus-example-tcs-huawei@workspace:examples/cactus-example-tcs-huawei\r\n\u2502  \u2514\u2500 eslint@npm:7.32.0 (via npm:7.32.0)\r\n\u2502\r\n\u251c\u2500 @hyperledger/cactus-plugin-htlc-coordinator-besu@workspace:extensions/cactus-plugin-htlc-coordinator-besu\r\n\u2502  \u2514\u2500 @hyperledger/cactus-test-plugin-htlc-eth-besu-erc20@workspace:packages/cactus-test-plugin-htlc-eth-besu-erc20 (via 2.0.0-alpha.1)\r\n\u2502\r\n\u251c\u2500 @hyperledger/cactus-plugin-odap-hermes@workspace:packages/cactus-plugin-odap-hermes\r\n\u2502  \u2514\u2500 @hyperledger/cactus-cmd-api-server@workspace:packages/cactus-cmd-api-server (via 2.0.0-alpha.1)\r\n\u2502\r\n\u251c\u2500 @hyperledger/cactus-test-api-client@workspace:packages/cactus-test-api-client\r\n\u2502  \u2514\u2500 @hyperledger/cactus-cmd-api-server@workspace:packages/cactus-cmd-api-server (via 2.0.0-alpha.1)\r\n\u2502\r\n\u251c\u2500 @hyperledger/cactus-test-cmd-api-server@workspace:packages/cactus-test-cmd-api-server\r\n\u2502  \u2514\u2500 @hyperledger/cactus-cmd-api-server@workspace:packages/cactus-cmd-api-server (via 2.0.0-alpha.1)\r\n\u2502\r\n\u251c\u2500 @hyperledger/cactus-test-plugin-consortium-manual@workspace:packages/cactus-test-plugin-consortium-manual\r\n\u2502  \u2514\u2500 @hyperledger/cactus-cmd-api-server@workspace:packages/cactus-cmd-api-server (via 2.0.0-alpha.1)\r\n\u2502\r\n\u251c\u2500 @hyperledger/cactus-test-plugin-htlc-eth-besu-erc20@workspace:packages/cactus-test-plugin-htlc-eth-besu-erc20\r\n\u2502\r\n\u251c\u2500 @hyperledger/cactus-test-plugin-htlc-eth-besu@workspace:packages/cactus-test-plugin-htlc-eth-besu\r\n\u2502  \u2514\u2500 @hyperledger/cactus-cmd-api-server@workspace:packages/cactus-cmd-api-server (via 2.0.0-alpha.1)\r\n\u2502\r\n\u251c\u2500 @hyperledger/cactus-test-plugin-ledger-connector-besu@workspace:packages/cactus-test-plugin-ledger-connector-besu\r\n\u2502  \u2514\u2500 @hyperledger/cactus-cmd-api-server@workspace:packages/cactus-cmd-api-server (via 2.0.0-alpha.1)\r\n\u2502\r\n\u251c\u2500 @hyperledger/cactus-test-plugin-ledger-connector-quorum@workspace:packages/cactus-test-plugin-ledger-connector-quorum\r\n\u2502  \u2514\u2500 @hyperledger/cactus-cmd-api-server@workspace:packages/cactus-cmd-api-server (via 2.0.0-alpha.1)\r\n\u2502\r\n\u251c\u2500 @hyperledger/cactus-test-verifier-client@workspace:packages/cactus-test-verifier-client\r\n\u2502  \u2514\u2500 @hyperledger/cactus-cmd-api-server@workspace:packages/cactus-cmd-api-server (via 2.0.0-alpha.1)\r\n\u2502\r\n\u2514\u2500 @hyperledger/cactus@workspace:.\r\n   \u2514\u2500 eslint@npm:7.32.0 (via npm:7.32.0)\r\n\r\n```\r\n\r\n[yarn_why_word_wrap.log](https://github.com/hyperledger/cacti/files/12147962/yarn_why_word_wrap.log)\r\n\r\n\r\n<!-- Edit the body of your new issue then click the \u2713 "Create Issue" button in the top right of the editor. The first line will be the issue title. Assignees and Labels follow after a blank line. Leave an empty line before beginning the body of the issue. -->',
        labels: [
            {
                id: 1629728751,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzUx',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/bug',
                name: 'bug',
                color: 'd73a4a',
                default: true,
                description: "Something isn't working",
            },
            {
                id: 1629728757,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzU3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue',
                name: 'good-first-issue',
                color: '7057ff',
                default: false,
                description: 'Good for newcomers',
            },
            {
                id: 1762140891,
                node_id: 'MDU6TGFiZWwxNzYyMTQwODkx',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/dependencies',
                name: 'dependencies',
                color: '0366d6',
                default: false,
                description: 'Pull requests that update a dependency file',
            },
            {
                id: 2085827790,
                node_id: 'MDU6TGFiZWwyMDg1ODI3Nzkw',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Security',
                name: 'Security',
                color: 'FF0000',
                default: false,
                description:
                    'Related to existing or potential security vulnerabilities',
            },
            {
                id: 2411211154,
                node_id: 'MDU6TGFiZWwyNDExMjExMTU0',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Hacktoberfest',
                name: 'Hacktoberfest',
                color: '9bc6f2',
                default: false,
                description:
                    'Hacktoberfest participants are welcome to take a stab at issues marked with this label.',
            },
            {
                id: 2924324338,
                node_id: 'MDU6TGFiZWwyOTI0MzI0MzM4',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue-400-expert',
                name: 'good-first-issue-400-expert',
                color: 'DF3D22',
                default: false,
                description: '',
            },
            {
                id: 3515616104,
                node_id: 'LA_kwDODOk1Zs7RjAto',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/P2',
                name: 'P2',
                color: 'D93F0B',
                default: false,
                description: 'Priority 2: High',
            },
        ],
        assignees: 1,
        comments: 0,
        created_at: '2023-07-24T16:20:40Z',
    },
    {
        issues: 'https://api.github.com/repos/hyperledger/cacti/issues/1713',
        title: 'build(deps): upgrade to TS 4.4 supply-chain-backend',
        body: null,
        labels: [
            {
                id: 1629728757,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzU3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue',
                name: 'good-first-issue',
                color: '7057ff',
                default: false,
                description: 'Good for newcomers',
            },
            {
                id: 1657071350,
                node_id: 'MDU6TGFiZWwxNjU3MDcxMzUw',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Nice-to-Have',
                name: 'Nice-to-Have',
                color: '5ea0bc',
                default: false,
                description: '',
            },
            {
                id: 1762140891,
                node_id: 'MDU6TGFiZWwxNzYyMTQwODkx',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/dependencies',
                name: 'dependencies',
                color: '0366d6',
                default: false,
                description: 'Pull requests that update a dependency file',
            },
            {
                id: 2092205837,
                node_id: 'MDU6TGFiZWwyMDkyMjA1ODM3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Developer_Experience',
                name: 'Developer_Experience',
                color: '5319e7',
                default: false,
                description: '',
            },
            {
                id: 2411211154,
                node_id: 'MDU6TGFiZWwyNDExMjExMTU0',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Hacktoberfest',
                name: 'Hacktoberfest',
                color: '9bc6f2',
                default: false,
                description:
                    'Hacktoberfest participants are welcome to take a stab at issues marked with this label.',
            },
            {
                id: 2924323155,
                node_id: 'MDU6TGFiZWwyOTI0MzIzMTU1',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue-200-intermediate',
                name: 'good-first-issue-200-intermediate',
                color: '8A9642',
                default: false,
                description: '',
            },
            {
                id: 3515617514,
                node_id: 'LA_kwDODOk1Zs7RjBDq',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/P4',
                name: 'P4',
                color: '1D76DB',
                default: false,
                description: 'Priority 4: Low',
            },
        ],
        assignees: 1,
        comments: 0,
        created_at: '2022-01-10T21:21:43Z',
    },
    {
        issues: 'https://api.github.com/repos/hyperledger/cacti/issues/1710',
        title: 'build(deps): upgrade to TS 4.4 carbon-accounting-backend',
        body: null,
        labels: [
            {
                id: 1629728757,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzU3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue',
                name: 'good-first-issue',
                color: '7057ff',
                default: false,
                description: 'Good for newcomers',
            },
            {
                id: 1657071350,
                node_id: 'MDU6TGFiZWwxNjU3MDcxMzUw',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Nice-to-Have',
                name: 'Nice-to-Have',
                color: '5ea0bc',
                default: false,
                description: '',
            },
            {
                id: 1762140891,
                node_id: 'MDU6TGFiZWwxNzYyMTQwODkx',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/dependencies',
                name: 'dependencies',
                color: '0366d6',
                default: false,
                description: 'Pull requests that update a dependency file',
            },
            {
                id: 2092205837,
                node_id: 'MDU6TGFiZWwyMDkyMjA1ODM3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Developer_Experience',
                name: 'Developer_Experience',
                color: '5319e7',
                default: false,
                description: '',
            },
            {
                id: 2411211154,
                node_id: 'MDU6TGFiZWwyNDExMjExMTU0',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Hacktoberfest',
                name: 'Hacktoberfest',
                color: '9bc6f2',
                default: false,
                description:
                    'Hacktoberfest participants are welcome to take a stab at issues marked with this label.',
            },
            {
                id: 2924323155,
                node_id: 'MDU6TGFiZWwyOTI0MzIzMTU1',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue-200-intermediate',
                name: 'good-first-issue-200-intermediate',
                color: '8A9642',
                default: false,
                description: '',
            },
            {
                id: 3515617514,
                node_id: 'LA_kwDODOk1Zs7RjBDq',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/P4',
                name: 'P4',
                color: '1D76DB',
                default: false,
                description: 'Priority 4: Low',
            },
        ],
        assignees: 1,
        comments: 0,
        created_at: '2022-01-10T21:19:20Z',
    },
    {
        issues: 'https://api.github.com/repos/hyperledger/cacti/issues/1653',
        title: 'fix(docs/examples): cockpitEnabled default value confusion',
        body: "There's a problem with the supply chain example app where some changes to the\nAPI server broke it, but the breakage could not be consistently reproduced nor\ncould we figure out what was the root cause.\n\nThere is a suspicion that it is due to the out of bounds yarn install process\nthat is executed from the `./examples/supply-chain-app/` directory (a `yarn install`)\nbut there's no proof for this just yet.\n\nIf the latter turns out to be the root cause then to fix this bug the fix would\nbe likely to abandon the directory structure where we have a separate\n`./examples/supply-chain-app/` that installs the `...-backend` package and\ninstead the documentation should instruct the readers to run the supply chain\nbackend package's entrypoint directly after a monorepo install so that the\ndependencies are in-bound instead of out-of-bound (e.g. the local changes\nare applied instead of the npm published packages being pulled down).\n\nSee the bottom comments on this PR: \nhttps://github.com/hyperledger/cactus/pull/1623\n\nSpecifically: \nhttps://github.com/hyperledger/cactus/pull/1623#issuecomment-989594072\nand\nhttps://github.com/hyperledger/cactus/pull/1623#issuecomment-992472050\n\n\n\n<!-- Edit the body of your new issue then click the \u2713 \"Create Issue\" button in the top right of the editor. The first line will be the issue title. Assignees and Labels follow after a blank line. Leave an empty line before beginning the body of the issue. -->",
        labels: [
            {
                id: 1629728751,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzUx',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/bug',
                name: 'bug',
                color: 'd73a4a',
                default: true,
                description: "Something isn't working",
            },
            {
                id: 1629728752,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzUy',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/documentation',
                name: 'documentation',
                color: '0075ca',
                default: true,
                description: 'Improvements or additions to documentation',
            },
            {
                id: 1629728757,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzU3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue',
                name: 'good-first-issue',
                color: '7057ff',
                default: false,
                description: 'Good for newcomers',
            },
            {
                id: 1629728759,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzU5',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/help%20wanted',
                name: 'help wanted',
                color: '008672',
                default: true,
                description: 'Extra attention is needed',
            },
            {
                id: 1657019279,
                node_id: 'MDU6TGFiZWwxNjU3MDE5Mjc5',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/API_Server',
                name: 'API_Server',
                color: '5fa5ce',
                default: false,
                description: '',
            },
            {
                id: 1657071350,
                node_id: 'MDU6TGFiZWwxNjU3MDcxMzUw',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Nice-to-Have',
                name: 'Nice-to-Have',
                color: '5ea0bc',
                default: false,
                description: '',
            },
            {
                id: 1762140891,
                node_id: 'MDU6TGFiZWwxNzYyMTQwODkx',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/dependencies',
                name: 'dependencies',
                color: '0366d6',
                default: false,
                description: 'Pull requests that update a dependency file',
            },
            {
                id: 2092205837,
                node_id: 'MDU6TGFiZWwyMDkyMjA1ODM3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Developer_Experience',
                name: 'Developer_Experience',
                color: '5319e7',
                default: false,
                description: '',
            },
            {
                id: 2411211154,
                node_id: 'MDU6TGFiZWwyNDExMjExMTU0',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Hacktoberfest',
                name: 'Hacktoberfest',
                color: '9bc6f2',
                default: false,
                description:
                    'Hacktoberfest participants are welcome to take a stab at issues marked with this label.',
            },
            {
                id: 2924324338,
                node_id: 'MDU6TGFiZWwyOTI0MzI0MzM4',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue-400-expert',
                name: 'good-first-issue-400-expert',
                color: 'DF3D22',
                default: false,
                description: '',
            },
            {
                id: 3475004911,
                node_id: 'LA_kwDODOk1Zs7PIF3v',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Tests',
                name: 'Tests',
                color: '1d76db',
                default: false,
                description:
                    'Anything related to tests be that automatic or manual, integration or unit, etc.',
            },
            {
                id: 3515617514,
                node_id: 'LA_kwDODOk1Zs7RjBDq',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/P4',
                name: 'P4',
                color: '1D76DB',
                default: false,
                description: 'Priority 4: Low',
            },
        ],
        assignees: 0,
        comments: 0,
        created_at: '2021-12-13T23:15:02Z',
    },
    {
        issues: 'https://api.github.com/repos/hyperledger/cacti/issues/1129',
        title: 'build(deps): upgrade to Typescript v4.4',
        body: "### Description\n\nCurrently we use tsc 4.3.x or similar but 4.4 is now in public beta[1] and have a couple of  very cool features that we want to start using as soon as possible to increase code quality in the project.\n\n[1]: https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-beta/\n\nSpecifically want to leverage this[2] feature which should make it so that if `Checks.truthy(...)` was used to assert that something is truthy, then in the following line the compiler will recognize this at compile time (which it hasn't done so before)\n\n[2]: https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-beta/#cfa-aliased-conditions\n\n### Acceptance Criteria\n1. Wait until 4.4 comes out of beta (but we can start testing today so that as soon as it hits GA, we can pull the plug with the upgrade)\n1. The Typescript compiler dependency is updated to 4.4\n2. CI is passing still\n\n```sh\n$ yarn lerna ls\nyarn run v1.18.0\nlerna notice cli v4.0.0\n@hyperledger/cactus-example-carbon-accounting-backend\n@hyperledger/cactus-example-carbon-accounting-business-logic-plugin\n@hyperledger/cactus-example-carbon-accounting-frontend\n@hyperledger/cactus-example-supply-chain-backend\n@hyperledger/cactus-example-supply-chain-business-logic-plugin\n@hyperledger/cactus-example-supply-chain-frontend\n@hyperledger/cactus-plugin-htlc-coordinator-besu\n@hyperledger/cactus-plugin-object-store-ipfs\n@hyperledger/cactus-api-client\n@hyperledger/cactus-cmd-api-server\n@hyperledger/cactus-common\n@hyperledger/cactus-core-api\n@hyperledger/cactus-core\n@hyperledger/cactus-plugin-consortium-manual\n@hyperledger/cactus-plugin-htlc-eth-besu-erc20\n@hyperledger/cactus-plugin-htlc-eth-besu\n@hyperledger/cactus-plugin-keychain-aws-sm\n@hyperledger/cactus-plugin-keychain-azure-kv\n@hyperledger/cactus-plugin-keychain-google-sm\n@hyperledger/cactus-plugin-keychain-memory-wasm\n@hyperledger/cactus-plugin-keychain-memory\n@hyperledger/cactus-plugin-keychain-vault\n@hyperledger/cactus-plugin-ledger-connector-besu\n@hyperledger/cactus-plugin-ledger-connector-corda\n@hyperledger/cactus-plugin-ledger-connector-fabric-socketio\n@hyperledger/cactus-plugin-ledger-connector-fabric\n@hyperledger/cactus-plugin-ledger-connector-go-ethereum-socketio\n@hyperledger/cactus-plugin-ledger-connector-iroha\n@hyperledger/cactus-plugin-ledger-connector-quorum\n@hyperledger/cactus-plugin-ledger-connector-sawtooth-socketio\n@hyperledger/cactus-plugin-ledger-connector-xdai\n@hyperledger/cactus-plugin-odap-hermes\n@hyperledger/cactus-test-api-client\n@hyperledger/cactus-test-cmd-api-server\n@hyperledger/cactus-test-plugin-consortium-manual\n@hyperledger/cactus-test-plugin-htlc-eth-besu-erc20\n@hyperledger/cactus-test-plugin-htlc-eth-besu\n@hyperledger/cactus-test-plugin-ledger-connector-besu\n@hyperledger/cactus-test-plugin-ledger-connector-quorum\n@hyperledger/cactus-test-tooling\nlerna success found 40 packages\nDone in 1.02s.\n```\n\ncc: @ty-lazar @Jeff-Ushry @twiggins120 @awadhana @Leeyoungone",
        labels: [
            {
                id: 1629728757,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzU3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue',
                name: 'good-first-issue',
                color: '7057ff',
                default: false,
                description: 'Good for newcomers',
            },
            {
                id: 1657071350,
                node_id: 'MDU6TGFiZWwxNjU3MDcxMzUw',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Nice-to-Have',
                name: 'Nice-to-Have',
                color: '5ea0bc',
                default: false,
                description: '',
            },
            {
                id: 1762140891,
                node_id: 'MDU6TGFiZWwxNzYyMTQwODkx',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/dependencies',
                name: 'dependencies',
                color: '0366d6',
                default: false,
                description: 'Pull requests that update a dependency file',
            },
            {
                id: 2092205837,
                node_id: 'MDU6TGFiZWwyMDkyMjA1ODM3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Developer_Experience',
                name: 'Developer_Experience',
                color: '5319e7',
                default: false,
                description: '',
            },
            {
                id: 2411211154,
                node_id: 'MDU6TGFiZWwyNDExMjExMTU0',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Hacktoberfest',
                name: 'Hacktoberfest',
                color: '9bc6f2',
                default: false,
                description:
                    'Hacktoberfest participants are welcome to take a stab at issues marked with this label.',
            },
            {
                id: 2727659927,
                node_id: 'MDU6TGFiZWwyNzI3NjU5OTI3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Epic',
                name: 'Epic',
                color: '3E4B9E',
                default: false,
                description: null,
            },
            {
                id: 2924323155,
                node_id: 'MDU6TGFiZWwyOTI0MzIzMTU1',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue-200-intermediate',
                name: 'good-first-issue-200-intermediate',
                color: '8A9642',
                default: false,
                description: '',
            },
        ],
        assignees: 1,
        comments: 1,
        created_at: '2021-07-13T21:05:19Z',
    },
    {
        issues: 'https://api.github.com/repos/hyperledger/cacti/issues/675',
        title: 'feat(consortium-indy): support consortium database indy backend',
        body: "**Is your feature request related to a problem? Please describe.**\n\nCurrently the only consortium plugin we have is the `manual` one which is very bare bones, basically the consortium plugin equivalent of what the in-memory keychain plugin is for keychains (e.g. it's mostly just good for writing tests without having to simulate costly additional infrastructure software for test cases).\n\n**Describe the solution you'd like**\n\nThe implementation should have the same endpoints/methods as the manual consortium plugin with the big difference being that the consortium database data is being pulled from an Indy ledger rather than from in-memory.\nThis way the consensus around who is in the consortium is outsourced to the Indy ledger (with all of it's problems which is great for us).\nEssentially the plugin is just a resolver for DIDs on Indy.\n\n**Describe alternatives you've considered**\n\nNothing, I'm pretty sure we need this.\n\n**Additional context**\n\nI put this under the epic of pluggable authentication but it's a slightly different topic (lines are blurred)\n\ncc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton @AzaharaC @jordigiam @kikoncuo @mwklein",
        labels: [
            {
                id: 1629728755,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzU1',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/enhancement',
                name: 'enhancement',
                color: 'a2eeef',
                default: true,
                description: 'New feature or request',
            },
            {
                id: 1629728757,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzU3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue',
                name: 'good-first-issue',
                color: '7057ff',
                default: false,
                description: 'Good for newcomers',
            },
            {
                id: 2411211154,
                node_id: 'MDU6TGFiZWwyNDExMjExMTU0',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Hacktoberfest',
                name: 'Hacktoberfest',
                color: '9bc6f2',
                default: false,
                description:
                    'Hacktoberfest participants are welcome to take a stab at issues marked with this label.',
            },
            {
                id: 2655484960,
                node_id: 'MDU6TGFiZWwyNjU1NDg0OTYw',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Core_API',
                name: 'Core_API',
                color: 'EB0D40',
                default: false,
                description: 'Changes related to the Core API Package',
            },
            {
                id: 2924324338,
                node_id: 'MDU6TGFiZWwyOTI0MzI0MzM4',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue-400-expert',
                name: 'good-first-issue-400-expert',
                color: 'DF3D22',
                default: false,
                description: '',
            },
            {
                id: 3515616541,
                node_id: 'LA_kwDODOk1Zs7RjA0d',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/P3',
                name: 'P3',
                color: 'FBCA04',
                default: false,
                description: 'Priority 3: Medium',
            },
        ],
        assignees: 0,
        comments: 0,
        created_at: '2021-03-16T19:41:40Z',
    },
    {
        issues: 'https://api.github.com/repos/hyperledger/cacti/issues/238',
        title: 'test: migrate from test runner tap to jest',
        body: '### Update 2021-08-09\r\n\r\nThis used to be about AVA but now is about Jest\r\n\r\n### Update 2020-11-02\r\n\r\nSwitched the target to AVA from jest, details below in comments.\r\n\r\n### Description\r\nAs a developer I want to be able to write unit tests for the universal packages that execute the same code both in NodeJS and in the browser so that I don\'t have to duplicate work in order to have test coverage for both platforms for the cross-platform packages.\r\n\r\nWhile working on the stable signature generation, we\'ve discovered that accidentally the wrong library was used initially (congratulations to Peter) which is called "tap" instead of "tape". They both do the same thing (test runners for TAP - `Test Anything Protocol`) but the `tap` library does not work in browsers while the `tape` library is, so to keep the build/test infrastructure of the project as simple as possible it would be the best to migrate to `tape` entirely since it anyway has support for `TAP` (the protocol)\r\n\r\nhttps://www.npmjs.com/package/ava\r\n\r\n### Acceptance Criteria\r\n1. Complexity of build/test scripts has not increased\r\n2. Tests for cross-platform packages such as `cactus-common` can be written once and ran "anywhere" (NodeJS, browser)\r\n3. Developer workflow has not lengthened, did not increase in complexity (from the human perspective, not code-wise that was mentioned in 1))\r\n\r\ncc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton @AzaharaC @jordigiam @kikoncuo',
        labels: [
            {
                id: 1629728751,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzUx',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/bug',
                name: 'bug',
                color: 'd73a4a',
                default: true,
                description: "Something isn't working",
            },
            {
                id: 1629728757,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzU3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue',
                name: 'good-first-issue',
                color: '7057ff',
                default: false,
                description: 'Good for newcomers',
            },
            {
                id: 1657071350,
                node_id: 'MDU6TGFiZWwxNjU3MDcxMzUw',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Nice-to-Have',
                name: 'Nice-to-Have',
                color: '5ea0bc',
                default: false,
                description: '',
            },
            {
                id: 1762140891,
                node_id: 'MDU6TGFiZWwxNzYyMTQwODkx',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/dependencies',
                name: 'dependencies',
                color: '0366d6',
                default: false,
                description: 'Pull requests that update a dependency file',
            },
            {
                id: 2411211154,
                node_id: 'MDU6TGFiZWwyNDExMjExMTU0',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Hacktoberfest',
                name: 'Hacktoberfest',
                color: '9bc6f2',
                default: false,
                description:
                    'Hacktoberfest participants are welcome to take a stab at issues marked with this label.',
            },
            {
                id: 2924323155,
                node_id: 'MDU6TGFiZWwyOTI0MzIzMTU1',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue-200-intermediate',
                name: 'good-first-issue-200-intermediate',
                color: '8A9642',
                default: false,
                description: '',
            },
            {
                id: 3475004911,
                node_id: 'LA_kwDODOk1Zs7PIF3v',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Tests',
                name: 'Tests',
                color: '1d76db',
                default: false,
                description:
                    'Anything related to tests be that automatic or manual, integration or unit, etc.',
            },
            {
                id: 3515617514,
                node_id: 'LA_kwDODOk1Zs7RjBDq',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/P4',
                name: 'P4',
                color: '1D76DB',
                default: false,
                description: 'Priority 4: Low',
            },
            {
                id: 5770656692,
                node_id: 'LA_kwDODOk1Zs8AAAABV_U7tA',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/backlog',
                name: 'backlog',
                color: '56552D',
                default: false,
                description:
                    'Tasks that are needed but we cannot prioritize them at present.',
            },
        ],
        assignees: 0,
        comments: 5,
        created_at: '2020-07-24T02:58:54Z',
    },
    {
        issues: 'https://api.github.com/repos/gopasspw/gopass/issues/1336',
        title: '[FR] Include commit hash in `gopass version`',
        body: "### Summary\r\n\r\n`gopass version` currently displays the version string as `1.9.0-git+HEAD`, which provides some indication of the version being used, but does not include critical information when debugging, such as the commit hash. Including this would simplify bug reports.\r\n\r\n### Steps To Reproduce\r\n\r\n```\r\n\u279c gopass version\r\ngopass 1.9.0-git+HEAD go1.14.2 linux amd64\r\n<root>     - gpg 2.2.20 - git 2.26.2 -   fs 0.1.0\r\nAvailable Crypto Backends: gpgcli, plain, xc\r\nAvailable RCS Backends: gitcli, noop\r\nAvailable Storage Backends: fs, inmem\r\n```\r\n\r\n### Expected behavior\r\n\r\nProvide the git sha in the version output, either by changing the format of the version string, or by providing a new row. For reference, some ideas:\r\n\r\n```\r\n\u279c git describe --long\r\nv1.9.0-8-g22fd3b9\r\n```\r\n\r\n```\r\ngopass 1.9.0-git+22fd3b9\r\n```\r\n\r\n### Environment\r\n\r\n```\r\n\u279c git log -1 --format='%H'\r\n22fd3b92ed6982e3f357b7e0f0ec355d22cac524\r\n\r\n\u279c ./gopass version\r\ngopass 1.9.0-git+HEAD go1.14.2 linux amd64\r\n<root>     - gpg 2.2.20 - git 2.26.2 -   fs 0.1.0\r\nAvailable Crypto Backends: gpgcli, plain, xc\r\nAvailable RCS Backends: gitcli, noop\r\nAvailable Storage Backends: fs, inmem\r\n\r\n\u279c uname -srm\r\nLinux 5.6.10-arch1-1 x86_64\r\n```",
        labels: [
            {
                id: 530697809,
                node_id: 'MDU6TGFiZWw1MzA2OTc4MDk=',
                url: 'https://api.github.com/repos/gopasspw/gopass/labels/help-wanted',
                name: 'help-wanted',
                color: '128A0C',
                default: false,
                description: '',
            },
            {
                id: 631481865,
                node_id: 'MDU6TGFiZWw2MzE0ODE4NjU=',
                url: 'https://api.github.com/repos/gopasspw/gopass/labels/bug',
                name: 'bug',
                color: 'f9d0c4',
                default: true,
                description: 'Defects',
            },
            {
                id: 2082119577,
                node_id: 'MDU6TGFiZWwyMDgyMTE5NTc3',
                url: 'https://api.github.com/repos/gopasspw/gopass/labels/good-first-issue',
                name: 'good-first-issue',
                color: '66e8b1',
                default: false,
                description: 'Good for beginners starting to contribute',
            },
            {
                id: 3473458689,
                node_id: 'LA_kwDOBM-8gs7PCMYB',
                url: 'https://api.github.com/repos/gopasspw/gopass/labels/Hacktoberfest',
                name: 'Hacktoberfest',
                color: 'D71EDB',
                default: false,
                description: '',
            },
        ],
        assignees: 0,
        comments: 3,
        created_at: '2020-05-07T12:12:06Z',
    },
];
