export const designIssues = [
    {
        issues: 'https://api.github.com/repos/hyperledger/cacti/issues/2767',
        title: 'fix(weaver): improper exception handling',
        body: '## Description\r\nStatic source code assessment has picked up a potential vulnerability regarding improper exception handling. The possible remediation for the same is to have it enclosed within a try catch block and handle the exceptions accordingly.\r\n\r\n## The report from which the above information was summarized\r\nRisk Rating: Low\r\nCategory: Security Misconfiguration\r\n\r\n### Description\r\nThe application performs some operation, such as database or file access, that could throw an exception. Since the application is not designed to properly handle the exception, the application could crash.\r\n\r\n### Impact\r\nAn attacker could maliciously cause an exception that could crash the application, potentially resulting in a denial of service (DoS) or unexpected behavior under certain erroneous conditions. Exceptions may also occur without any malicious intervention, resulting in general instability.\r\n\r\n### Remediation Recommendation\r\nAny method that could cause an exception should be wrapped in a try-catch block that:\r\n\u2022 Explicitly handles expected exceptions.\r\n\u2022 Includes a default solution to explicitly handle unexpected exceptions.\r\n\r\n### Affected files (path - line number)\r\n\r\nweaver/sdks/corda/src/main/kotlin/org/hyperledger/cacti/weaver/sdk/corda/CredentialsExtractor.java - 294,295\r\n\r\n## Snapshot of the sourcecode at the time of scan\r\n\r\n<img width="605" alt="image" src="https://github.com/hyperledger/cacti/assets/56861721/e35e510c-a8a5-46b8-a30f-d4c1c59e177b">\r\n---\r\n\r\nSource: `APP PE Hyperledger Cacti v2.0.0 - Static Application Assessment Report.odt`\r\n\r\ncc: @takeutak @izuru0 @outSH @petermetz ',
        labels: [
            {
                id: 1629728757,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzU3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue',
                name: 'good-first-issue',
                color: '7057ff',
                default: false,
                description: 'Good for newcomers',
            },
            {
                id: 2085827790,
                node_id: 'MDU6TGFiZWwyMDg1ODI3Nzkw',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Security',
                name: 'Security',
                color: 'FF0000',
                default: false,
                description:
                    'Related to existing or potential security vulnerabilities',
            },
            {
                id: 2411211154,
                node_id: 'MDU6TGFiZWwyNDExMjExMTU0',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Hacktoberfest',
                name: 'Hacktoberfest',
                color: '9bc6f2',
                default: false,
                description:
                    'Hacktoberfest participants are welcome to take a stab at issues marked with this label.',
            },
            {
                id: 2924323155,
                node_id: 'MDU6TGFiZWwyOTI0MzIzMTU1',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue-200-intermediate',
                name: 'good-first-issue-200-intermediate',
                color: '8A9642',
                default: false,
                description: '',
            },
            {
                id: 3531600086,
                node_id: 'LA_kwDODOk1Zs7Sf_DW',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Weaver',
                name: 'Weaver',
                color: '7CEC52',
                default: false,
                description:
                    'Tasks related to the future of Cactus & Weaver together.',
            },
        ],
        assignees: 1,
        comments: 4,
        created_at: '2023-10-11T08:25:07Z',
    },
    {
        issues: 'https://api.github.com/repos/hyperledger/cacti/issues/2765',
        title: 'fix(weaver): usage of weak PRNG ',
        body: '## Description\r\nStatic source code assessment has picked up a potential vulnerability regarding use of weak pseudo RNG. Use of secure pseudo random number generators rather than using basic random methods can fix the above vulnerability\r\n\r\n## The report from which the above information was summarized\r\nRisk Rating: Low\r\nCategory: Security Misconfiguration\r\n\r\n### Description\r\nThe application uses a weak method of generating pseudo-random values, such that other numbers could be determined from a relatively small sample size. Since the pseudo-random number generator used is designed for statistically uniform distribution of values, it is approximately deterministic. Thus, after collecting a few generated values, it would be possible for an attacker to calculate past or future values. These values are then used as parameters in a cryptographic function. If an attacker were to obtain the original value from the weak PRNG, they may be able to predict or crack values produced by the cryptographic function.\r\n\r\n### Impact\r\nDepending on what this random value is used for, an attacker with knowledge of the PRNG used would be able to predict the next values generated, or previously generated values, based on sources often used to derive certain randomness; however, while they may seem random, large statistical samples would demonstrate that they are insufficiently random, producing a much smaller space of possible "random" values than a truly random sample would. In the context of cryptography, this could enable an attacker to derive or guess the value, and thus crack the cryptographic mechanism or its outputs.\r\n\r\n### Remediation Recommendation\r\n\u2022 Always use a cryptographically secure pseudo-random number generator, instead of basic random methods, particularly when dealing with a security context such as cryptographic functions\r\n\u2022 Use the cryptorandom generator that is built-in to your language or platform, and ensure it is securely seeded. Do not seed the generator with a weak, non-random seed. (In most cases, the default is securely random). \r\n\u2022 Ensure you use a long enough random value, thus making brute-force attacks unfeasible.\r\n\r\n### Affected files (path - line number)\r\n\r\nweaver/core/network/fabric-interop-cc/contracts/interop/certificate_utils.go - 304\r\nweaver/sdks/corda/src/main/kotlin/org/hyperledger/cacti/weaver/sdk/corda/HashFunctions.kt - 46\r\nweaver/sdks/fabric/interoperation-node-sdk/src/eciesCrypto.js - 177\r\n\r\n## Snapshot of the sourcecode at the time of scan\r\n\r\n<img width="610" alt="image" src="https://github.com/hyperledger/cacti/assets/56861721/a7cfee3a-39c2-46d2-9732-9548991d575c">\r\n<img width="620" alt="image" src="https://github.com/hyperledger/cacti/assets/56861721/4e721822-9bd2-4fa0-a6f4-9e350f9262d1">\r\n<img width="558" alt="image" src="https://github.com/hyperledger/cacti/assets/56861721/3a5e2ace-21c7-4745-baf3-04f2ea30c7d1">\r\n\r\n---\r\n\r\nSource: `APP PE Hyperledger Cacti v2.0.0 - Static Application Assessment Report.odt`\r\n\r\ncc: @takeutak @izuru0 @outSH @petermetz ',
        labels: [
            {
                id: 1629728757,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzU3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue',
                name: 'good-first-issue',
                color: '7057ff',
                default: false,
                description: 'Good for newcomers',
            },
            {
                id: 2085827790,
                node_id: 'MDU6TGFiZWwyMDg1ODI3Nzkw',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Security',
                name: 'Security',
                color: 'FF0000',
                default: false,
                description:
                    'Related to existing or potential security vulnerabilities',
            },
            {
                id: 2411211154,
                node_id: 'MDU6TGFiZWwyNDExMjExMTU0',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Hacktoberfest',
                name: 'Hacktoberfest',
                color: '9bc6f2',
                default: false,
                description:
                    'Hacktoberfest participants are welcome to take a stab at issues marked with this label.',
            },
            {
                id: 2924323587,
                node_id: 'MDU6TGFiZWwyOTI0MzIzNTg3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue-300-advanced',
                name: 'good-first-issue-300-advanced',
                color: 'D65806',
                default: false,
                description: '',
            },
            {
                id: 2924324338,
                node_id: 'MDU6TGFiZWwyOTI0MzI0MzM4',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue-400-expert',
                name: 'good-first-issue-400-expert',
                color: 'DF3D22',
                default: false,
                description: '',
            },
            {
                id: 3515617514,
                node_id: 'LA_kwDODOk1Zs7RjBDq',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/P4',
                name: 'P4',
                color: '1D76DB',
                default: false,
                description: 'Priority 4: Low',
            },
            {
                id: 3531600086,
                node_id: 'LA_kwDODOk1Zs7Sf_DW',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Weaver',
                name: 'Weaver',
                color: '7CEC52',
                default: false,
                description:
                    'Tasks related to the future of Cactus & Weaver together.',
            },
        ],
        assignees: 0,
        comments: 0,
        created_at: '2023-10-11T08:17:27Z',
    },
    {
        issues: 'https://api.github.com/repos/hginit/hginit.github.io/issues/4',
        title: 'Responsive Design: Fix home navigation scroll',
        body: 'The scroll for the listing on the home page is not natural. It should instead be top-to-bottom on the homepage.\r\n\r\n<img width="287" alt="image" src="https://user-images.githubusercontent.com/584253/214348974-d0ede8c4-654e-4293-ade1-ac4656cdce9e.png">\r\n',
        labels: [
            {
                id: 5074122132,
                node_id: 'LA_kwDOEmht688AAAABLnD1lA',
                url: 'https://api.github.com/repos/hginit/hginit.github.io/labels/hacktoberfest',
                name: 'hacktoberfest',
                color: '77E6F6',
                default: false,
                description: '',
            },
            {
                id: 5074122502,
                node_id: 'LA_kwDOEmht688AAAABLnD3Bg',
                url: 'https://api.github.com/repos/hginit/hginit.github.io/labels/good-first-issue',
                name: 'good-first-issue',
                color: 'F77CEE',
                default: false,
                description: '',
            },
        ],
        assignees: 0,
        comments: 3,
        created_at: '2023-01-24T16:22:39Z',
    },
    {
        issues: 'https://api.github.com/repos/hginit/hginit.github.io/issues/2',
        title: 'Responsive Design: Top nav bar',
        body: 'Topbar should be sticky, and responsive for mobile layouts. It should list links top to bottom, instead of left to right.\r\n\r\n<img width="266" alt="image" src="https://user-images.githubusercontent.com/584253/214347938-a86e3579-6817-42fc-8f09-6daa15d48c9e.png">\r\n',
        labels: [
            {
                id: 5074122132,
                node_id: 'LA_kwDOEmht688AAAABLnD1lA',
                url: 'https://api.github.com/repos/hginit/hginit.github.io/labels/hacktoberfest',
                name: 'hacktoberfest',
                color: '77E6F6',
                default: false,
                description: '',
            },
            {
                id: 5074122502,
                node_id: 'LA_kwDOEmht688AAAABLnD3Bg',
                url: 'https://api.github.com/repos/hginit/hginit.github.io/labels/good-first-issue',
                name: 'good-first-issue',
                color: 'F77CEE',
                default: false,
                description: '',
            },
        ],
        assignees: 0,
        comments: 1,
        created_at: '2023-01-24T16:18:39Z',
    },
    {
        issues: 'https://api.github.com/repos/Gautam-Arora24/pointer.js/issues/3',
        title: 'Need more designs for static cursors.',
        body: 'Looking for `designers` who can help design some new trendy cursors for the library.',
        labels: [
            {
                id: 3994027987,
                node_id: 'LA_kwDOHG62PM7uEAfT',
                url: 'https://api.github.com/repos/Gautam-Arora24/pointer.js/labels/design',
                name: 'design',
                color: '909D17',
                default: false,
                description: '',
            },
            {
                id: 3994028254,
                node_id: 'LA_kwDOHG62PM7uEAje',
                url: 'https://api.github.com/repos/Gautam-Arora24/pointer.js/labels/good-first-issue',
                name: 'good-first-issue',
                color: 'A2CCAC',
                default: false,
                description: '',
            },
            {
                id: 4600127813,
                node_id: 'LA_kwDOHG62PM8AAAABEjBhRQ',
                url: 'https://api.github.com/repos/Gautam-Arora24/pointer.js/labels/hacktoberfest',
                name: 'hacktoberfest',
                color: '10DF5B',
                default: false,
                description: '',
            },
        ],
        assignees: 0,
        comments: 12,
        created_at: '2022-04-03T13:03:56Z',
    },
    {
        issues: 'https://api.github.com/repos/endoflife-date/endoflife.date/issues/408',
        title: '\ud83d\ude80\ud83d\ude80 README for Hacktoberfest Participants \ud83d\ude80\ud83d\ude80',
        body: "Welcome to Hacktoberfest 2022! endoflife.date is a simple informational (open-source) website that details the support lifecycles of various products. If you are interesting in earning [some swag](https://hacktoberfest.digitalocean.com/resources/participation) and helping this project, read on. Please read this document completely before filing a Pull Request.\r\n\r\nBefore you get started, get to know the project a little bit. Open [endoflife.date](https://endoflife.date) and browse around a little bit. Take a look at some of these recently merged PRs to get a better idea: [#1598](https://github.com/endoflife-date/endoflife.date/pull/1598), [#1603](https://github.com/endoflife-date/endoflife.date/pull/1603), [#1552](https://github.com/endoflife-date/endoflife.date/pull/1552), [#1596](https://github.com/endoflife-date/endoflife.date/pull/1596).\r\n\r\n## About the codebase\r\n\r\nendoflife.date is built using [Jekyll](https://jekyllrb.com/) - the Ruby static site builder that powers GitHub Pages. The site is built and deployed to [Netlify](https://netlify.com). Since the site is mostly informational, you _don't need programming skills to contribute to the project_.\r\n\r\n## \ud83d\udc7e Recommended PRs and Changes\r\n\r\nHere's some recommendations for good first contributions to the codebase. We've also made sure that there are enough details on linked issues for beginners to start working on them.\r\n\r\n### \ud83c\udd95 Release Updates\r\n\r\nThe bulk majority of PRs to the project are trivial release update PRs. You can see previously merged PRs [using the `release-updates`](https://github.com/endoflife-date/endoflife.date/pulls?q=is%3Apr+sort%3Aupdated-desc+label%3Arelease-updates+is%3Aclosed) label as a guide. If a new release has been made for a project that is currently being tracked on the endoflife.date website, we welcome PRs for updating the data around for that new release. If you make such a PR, here's a short checklist to follow:\r\n\r\n- Have you updated _all of the release cycles_ that might have got an update?\r\n- Has any previous release reached end of life? Does that need updating?\r\n- If it's a new major release (which needs a new release cycle to be added), do we have a corresponding EoL dates for it?\r\n- Is the page automatically updated? If so, our automation bot might beat you to it.\r\n\r\n### \ud83d\udc85 Design and Layout Changes\r\n\r\nIf you're comfortable with SASS, Jekyll, HTML, Javascript - we're looking for some help around easy to fix design issues on the website. Make sure you've read through the [HACKING.md](https://github.com/endoflife-date/endoflife.date/blob/master/HACKING.md) file and setup the project locally before you start working on these.\r\n\r\nNote that we are looking for good clean code, and unmaintainable hacks might be rejected. Make sure your changes align with the Jekyll Philosophy (for eg using SCSS mixings and Jekyll best practices).\r\n\r\nClick through the following issues to read more.\r\n\r\n- [Autofocus to search input](https://github.com/endoflife-date/endoflife.date/issues/367)\r\n- [Hide old releases by default](https://github.com/endoflife-date/endoflife.date/issues/50)\r\n- [Add Product Logo in the sidebar](https://github.com/endoflife-date/endoflife.date/issues/283)\r\n\r\nThe following require a better understanding of Jekyll and Liquid templating. A simple easy-medium-hard rating is here to help you decide as well.:\r\n\r\n- [Update API to use ChangeLog template](https://github.com/endoflife-date/endoflife.date/issues/394) (Medium)\r\n- [Generate RSS Feed for every product](https://github.com/endoflife-date/endoflife.date/issues/48) (Hard)\r\n- [Add a Last Modified Date](https://github.com/endoflife-date/endoflife.date/issues/70) (Easy)\r\n- [Support LTS Dates](https://github.com/endoflife-date/endoflife.date/issues/156) (Medium)\r\n- [Support Dark Mode](https://github.com/just-the-docs/just-the-docs/issues/234) (Medium)\r\n\r\n### \ud83e\udd84 Adding New Products\r\n\r\nThe [Guiding Principles](https://github.com/endoflife-date/endoflife.date/wiki/Guiding-Principles) of the project state that \"it exists to be useful to the readers\". The more products we track, the more helpful we become. We're currently tracking 66 products, and we'd like to track more. Here's a list of suggested products that we think are worth tracking. File a PR for any of these! A few have links to upstream project websites to help you find the actual dates for these projects.\r\n\r\n- [Azure Kubernetes Service](https://github.com/endoflife-date/endoflife.date/issues/133)\r\n- Internet Explorer\r\n- ~~Apache Tomcat~~\r\n- iPad\r\n- ~~Samsung Galaxy Phones~~\r\n- [Plesk](https://www.plesk.com/lifecycle-policy/)\r\n- ~~Linux Mint~~\r\n- [cPanel](https://docs.cpanel.net/knowledge-base/cpanel-product/product-versions-and-the-release-process/)\r\n- ~~VMWare ESXi~~\r\n- ~~VMWare Horizon (#540)~~\r\n- ~~VMWare Citrix (#540)~~\r\n- ~~[Microsoft Exchange](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/supportability-matrix?view=exchserver-2019), [more](https://docs.microsoft.com/en-us/microsoft-365/enterprise/exchange-2010-end-of-support?view=o365-worldwide)~~\r\n- Quickbooks\r\n- Various [Forza Games](https://culturedvultures.com/forza-end-of-life-process/)\r\n- Movable Type\r\n- Apache Cassandra\r\n- Apache Mesos\r\n- Rancher\r\n- ~~Docker~~\r\n- Ceph\r\n- Postfix\r\n- Envoy\r\n- ~~HAProxy~~\r\n- ~~Apache (the webserver)~~\r\n- Many other Atlassian, Oracle, and IBM products.\r\n\r\n> (This list is based on personal observations, requests from users, google keyword research, and [this list maintained by @witchcraze](https://qiita.com/witchcraze/items/af8ac5da5948ff6a609e).\r\n\r\nIf you'd like to create a new page for something that is not on the above list - that's okay as well. We haven't had to reject a product so far, and doubt we will reject what you propose. Just make sure it is a _well known product_. We are open to accepting devices, frameworks, languages, operating-systems, applications, and pretty much everything that has a support lifecycle of some sort. If in doubt, ask us.\r\n\r\nIn creating a new page, make sure you read through [CONTRIBUTING.md](https://github.com/endoflife-date/endoflife.date/blob/master/CONTRIBUTING.md) to understand the file structure, and go through a few of previously merged PRs [with the label `new-product`](https://github.com/endoflife-date/endoflife.date/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+label%3Anew-product). Also, please read through the [Guiding Principles](https://github.com/endoflife-date/endoflife.date/wiki/Guiding-Principles) to make sure your writing style and content is good enough and matches the rest of the site. Reading these will help you get onboarded faster and make sure that your PR sees a speedy merge.\r\n\r\n### \ud83d\udcdd Changelog Links\r\n\r\nNot all of the products on the website have their latest releases linked to a relevant page. Usually this is the changelog for that release or a blog post.\r\n\r\nSee this issue for all the details: https://github.com/endoflife-date/endoflife.date/issues/39\r\n\r\n### Miscellaneous Contributions\r\n\r\nWe have issues labelled as [good first issue](https://github.com/endoflife-date/endoflife.date/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) for easy to pick up contributions. All of these have a detailed comment at the bottom telling exactly what needs to be done, and what skills might be needed.\r\n\r\nIf you'd like to suggest a new product to track, please create a new issue. Issues are also welcome if you have any suggestions for the website in general - around design, visibility, accessibility, usability for eg.\r\n\r\n## \ud83d\udc69\u200d\ud83c\udf93 How to file a Pull Request\r\n\r\nFor most trivial changes (mainly release update and small content fixes), you can make these using the GitHub UI itself - just to to the relevant file and click the Pencil icon:\r\n\r\n![image](https://user-images.githubusercontent.com/584253/134509844-197cb6fb-5d6d-4d8b-bf0b-84d6f0cf6989.png)\r\n\r\nEdit the file accordingly, then type a good title and description for your changes:\r\n\r\n![image](https://user-images.githubusercontent.com/584253/134510105-1efacea4-8044-4b24-ae83-237539442fb6.png)\r\n\r\nClick \"Propose Changes\" and then review the changes you've made before clicking \"Create Pull Request\". If you still need to make more changes, create a \"Draft Pull Request\" by clicking the dropdown on the \"Create Pull Request\" button:\r\n\r\n![](https://docs.github.com/assets/images/help/pull_requests/pullrequest-send.png).\r\n\r\nYou can change the PR from a Draft PR to a ready PR afterwards.\r\n\r\n## \u2705 Validating your changes\r\n\r\nOnce you file your Pull Request, Netlify will provide a list of checks for your changes. If one of the checks is failed, you can click Details and see through the errors, or one of the Maintainers will be there to help you soon.\r\n\r\nIf all of the checks pass, you can click the \"Details\" link on the \"Deploy Preview\" Status Check to see a preview of the website _with your changes_.\r\n\r\n![image](https://user-images.githubusercontent.com/584253/134535142-7d1170b7-16f4-4cd3-987e-e890b76098d5.png)\r\n\r\nClick through, and validate your changes. Click all the links in the page you've changed and make sure they're not broken.\r\n\r\n## \ud83d\udcd1 Suggested Reading\r\n\r\nPlease make sure that you've gone through the Hacktoberfest [Quality Standards](https://hacktoberfest.digitalocean.com/resources/qualitystandards) and the [Participation Guidelines](https://hacktoberfest.digitalocean.com/resources/participation).\r\n\r\nAdditionally, we have the following documents which should help you get familiar with the project and the codebase. You don't need to read all of these, and we've linked these docs above in cases where you must read any of them.\r\n\r\n- [HACKING.md](https://github.com/endoflife-date/endoflife.date/blob/master/HACKING.md) contains instructions on setting up the codebase locally with Jekyll. Read this if you're planning to make complex changes or setting up the project locally.\r\n- [Guiding Principles](https://github.com/endoflife-date/endoflife.date/wiki/Guiding-Principles) - These help us make decisions around the content we have. If you'd like to make sure your PR gets a speedy approval, please read these to ensure your changes are aligned with the rest of the content. This is _especially important if you are making non-trivial changes_ that deal with the content or add a new product.\r\n- [CONTRIBUTING.md](https://github.com/endoflife-date/endoflife.date/blob/master/CONTRIBUTING.md) - This walks you through the structure each product page takes, in detailed comments. Do read this if you are _adding a new product page to the website_.\r\n- [Code of Conduct](https://github.com/endoflife-date/endoflife.date/blob/master/CODE-OF-CONDUCT.md) - This project follows the Contributor Covenant Code of Conduct, which you can read at this link. You must read this and agree to abide by this at all times in your interactions with this project and its community.\r\n\r\n# \u2753 Questions?\r\n\r\nIf you have any questions, please [create a new Discussion under the Hacktoberfest category](https://github.com/endoflife-date/endoflife.date/discussions/new?category=hacktoberfest). If you are picking up a new task, first check if there is already a PR for the same, and if not - [create a Draft Pull Request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) as soon as you can so others do not pick up the same task.\r\n\r\nThis issue is pinned and locked permitted to keep this clean for Hacktoberfest related announcements. Please [create a new Discussions](https://github.com/endoflife-date/endoflife.date/discussions/new?category=hacktoberfest) in the Hacktoberfest category instead.",
        labels: [
            {
                id: 3405392125,
                node_id: 'LA_kwDOC0FNEs7K-ij9',
                url: 'https://api.github.com/repos/endoflife-date/endoflife.date/labels/Hacktoberfest',
                name: 'Hacktoberfest',
                color: '430C99',
                default: false,
                description:
                    'Issues that are good first picks for Hacktoberfest participants',
            },
            {
                id: 5080381010,
                node_id: 'LA_kwDOC0FNEs8AAAABLtB2Ug',
                url: 'https://api.github.com/repos/endoflife-date/endoflife.date/labels/good-first-issue',
                name: 'good-first-issue',
                color: 'D55ADB',
                default: false,
                description: 'Good for newcomers',
            },
        ],
        assignees: 0,
        comments: 0,
        created_at: '2021-09-23T15:59:32Z',
    },
    {
        issues: 'https://api.github.com/repos/endoflife-date/endoflife.date/issues/283',
        title: 'Adding Product Logo in sidebar',
        body: 'It will be nice to add a new part for tools sections called productLogo or logo so\r\nwe can put logos with svg formated logo links ( which must be creative common or any open license) that will improve its look visually\r\n\r\n![](https://user-images.githubusercontent.com/112882/124751786-b51d8600-df2f-11eb-9331-ad34d94e127b.png)',
        labels: [
            {
                id: 3405392125,
                node_id: 'LA_kwDOC0FNEs7K-ij9',
                url: 'https://api.github.com/repos/endoflife-date/endoflife.date/labels/Hacktoberfest',
                name: 'Hacktoberfest',
                color: '430C99',
                default: false,
                description:
                    'Issues that are good first picks for Hacktoberfest participants',
            },
            {
                id: 5080381010,
                node_id: 'LA_kwDOC0FNEs8AAAABLtB2Ug',
                url: 'https://api.github.com/repos/endoflife-date/endoflife.date/labels/good-first-issue',
                name: 'good-first-issue',
                color: 'D55ADB',
                default: false,
                description: 'Good for newcomers',
            },
        ],
        assignees: 0,
        comments: 15,
        created_at: '2021-07-05T10:27:21Z',
    },
    {
        issues: 'https://api.github.com/repos/Umuzi-org/ACN-syllabus/issues/50',
        title: 'SQL schema design project',
        body: 'Think of an interesting schema design project that covers the concepts from #49  \r\n\r\nThings to note:\r\n- dont hold their hands too much! We are dealing with juniors, BUT they need to learn to solve problems themselves. \r\n- some of the people using this are not first language english speakers. So please keep your language simple',
        labels: [
            {
                id: 2394110766,
                node_id: 'MDU6TGFiZWwyMzk0MTEwNzY2',
                url: 'https://api.github.com/repos/Umuzi-org/ACN-syllabus/labels/hacktoberfest',
                name: 'hacktoberfest',
                color: '5319e7',
                default: false,
                description: '',
            },
            {
                id: 2400793684,
                node_id: 'MDU6TGFiZWwyNDAwNzkzNjg0',
                url: 'https://api.github.com/repos/Umuzi-org/ACN-syllabus/labels/good-first-issue',
                name: 'good-first-issue',
                color: '29bc9f',
                default: false,
                description: '',
            },
            {
                id: 2400794444,
                node_id: 'MDU6TGFiZWwyNDAwNzk0NDQ0',
                url: 'https://api.github.com/repos/Umuzi-org/ACN-syllabus/labels/status/help-wanted',
                name: 'status/help-wanted',
                color: 'd091f2',
                default: false,
                description: '',
            },
            {
                id: 2414288802,
                node_id: 'MDU6TGFiZWwyNDE0Mjg4ODAy',
                url: 'https://api.github.com/repos/Umuzi-org/ACN-syllabus/labels/experienced-devs-only',
                name: 'experienced-devs-only',
                color: '59f989',
                default: false,
                description: '',
            },
        ],
        assignees: 0,
        comments: 0,
        created_at: '2020-10-10T02:30:42Z',
    },
    {
        issues: 'https://api.github.com/repos/Umuzi-org/ACN-syllabus/issues/49',
        title: 'Add sql TOPIC about schema design',
        body: 'Once a student knows how to create a table with the CREATE TABLE statement, they should be able to move onto this.\r\n\r\nWe need to make sure our bases are covered. We dont need to get people to know about the normal forms or star schemas or anything like that., Rather focus on foundational concepts.\r\n\r\nIn this topic cover:\r\n\r\n1. sensible naming conventions\r\n\r\neg:\r\n\r\n```\r\ntable name = users  (plural)\r\nprimary key = id   \r\n\r\ntable name = tickets (plural)\r\nprimary key = id (consistent)\r\nforeign key to user table = user_id (dead obvious what we are referring to. We are referring to a single user therefore singular)   \r\n ```\r\n\r\n2. One to many relationships\r\n3. One to one relationships\r\n4. Many to many relationships\r\n5. DRY data (which is the same as normalisation - by default we would want to have one piece of info represented once)\r\n',
        labels: [
            {
                id: 2394110766,
                node_id: 'MDU6TGFiZWwyMzk0MTEwNzY2',
                url: 'https://api.github.com/repos/Umuzi-org/ACN-syllabus/labels/hacktoberfest',
                name: 'hacktoberfest',
                color: '5319e7',
                default: false,
                description: '',
            },
            {
                id: 2400793684,
                node_id: 'MDU6TGFiZWwyNDAwNzkzNjg0',
                url: 'https://api.github.com/repos/Umuzi-org/ACN-syllabus/labels/good-first-issue',
                name: 'good-first-issue',
                color: '29bc9f',
                default: false,
                description: '',
            },
            {
                id: 2400794105,
                node_id: 'MDU6TGFiZWwyNDAwNzk0MTA1',
                url: 'https://api.github.com/repos/Umuzi-org/ACN-syllabus/labels/status/claimed',
                name: 'status/claimed',
                color: '9bc645',
                default: false,
                description: '',
            },
            {
                id: 2414288802,
                node_id: 'MDU6TGFiZWwyNDE0Mjg4ODAy',
                url: 'https://api.github.com/repos/Umuzi-org/ACN-syllabus/labels/experienced-devs-only',
                name: 'experienced-devs-only',
                color: '59f989',
                default: false,
                description: '',
            },
        ],
        assignees: 0,
        comments: 1,
        created_at: '2020-10-10T02:28:20Z',
    },
    {
        issues: 'https://api.github.com/repos/Mte90/GlotDict/issues/237',
        title: 'Enhancement - Note Warnings in same fashion as GlotPress',
        body: 'With the new design of translate.wp.org it would be nice to flag GlotDict warnings in the same fashion.\r\n\r\n<img width="265" alt="Screen Shot 2019-06-04 at 10 53 57 AM" src="https://user-images.githubusercontent.com/8726005/58902053-3c480200-86b7-11e9-8546-b5ffab4f1f3d.png">\r\n',
        labels: [
            {
                id: 327570071,
                node_id: 'MDU6TGFiZWwzMjc1NzAwNzE=',
                url: 'https://api.github.com/repos/Mte90/GlotDict/labels/enhancement',
                name: 'enhancement',
                color: '84b6eb',
                default: true,
                description: null,
            },
            {
                id: 705607552,
                node_id: 'MDU6TGFiZWw3MDU2MDc1NTI=',
                url: 'https://api.github.com/repos/Mte90/GlotDict/labels/hacktoberfest',
                name: 'hacktoberfest',
                color: 'e99695',
                default: false,
                description: null,
            },
            {
                id: 983873589,
                node_id: 'MDU6TGFiZWw5ODM4NzM1ODk=',
                url: 'https://api.github.com/repos/Mte90/GlotDict/labels/good-first-issue',
                name: 'good-first-issue',
                color: '5319e7',
                default: false,
                description: '',
            },
        ],
        assignees: 0,
        comments: 0,
        created_at: '2019-06-04T17:55:20Z',
    },
];
