export const devOpsIssues = [
    {
        issues: 'https://api.github.com/repos/hyperledger/cacti/issues/860',
        title: 'docs(examples): carbon accounting microk8s deployment files',
        body: "### Description\r\nAs a contributor/maintainer I want to be able to have an easy way of deploying the carbon accounting example to a microk8s Kubernetes cluster so that I can see a good example of how projects using Cactus can be operated in a data center environment.\r\n\r\nWe start with microk8s because that's the default Ubuntu k8s distro and our CI pipeline is built on top of Ubuntu already so this should eliminate a few extra complexities compared to focusing on other k8s distros instead since microk8s could be tested on a Windows computer as well via WSL 2\r\n\r\nWhile working on this issue it is likely that other shortcomings will be unearthed in the code-base, things that could warrant their own user stories/bugs as well and therefore the classification of this issue is \"400-expert\" because there's no major change in the code, but you'll need to be an expert in a few different things to progress with this.\r\n\r\n### Acceptance Criteria\r\n1. There's either a Helm chart defined or a KNative file defined and a top level npm script that performs the deployment to a microk8s Kubernetes cluster\r\n2. The process of performing the deployment/testing it out is documented to the extent that it should be workable from the point where someone has an Ubuntu machine fresh out of the oven so to speak. For setting up the k8s cluster itself it's sufficient to reference the documentation of microk8s itself, but the specific addons we need have to be documented of course.\r\n\r\ncc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton @AzaharaC @jordigiam @kikoncuo @jagpreetsinghsasan @arnab-roy\r\n",
        labels: [
            {
                id: 1629728752,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzUy',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/documentation',
                name: 'documentation',
                color: '0075ca',
                default: true,
                description: 'Improvements or additions to documentation',
            },
            {
                id: 1629728757,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzU3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue',
                name: 'good-first-issue',
                color: '7057ff',
                default: false,
                description: 'Good for newcomers',
            },
            {
                id: 1762140891,
                node_id: 'MDU6TGFiZWwxNzYyMTQwODkx',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/dependencies',
                name: 'dependencies',
                color: '0366d6',
                default: false,
                description: 'Pull requests that update a dependency file',
            },
            {
                id: 2092205837,
                node_id: 'MDU6TGFiZWwyMDkyMjA1ODM3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Developer_Experience',
                name: 'Developer_Experience',
                color: '5319e7',
                default: false,
                description: '',
            },
            {
                id: 2411211154,
                node_id: 'MDU6TGFiZWwyNDExMjExMTU0',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Hacktoberfest',
                name: 'Hacktoberfest',
                color: '9bc6f2',
                default: false,
                description:
                    'Hacktoberfest participants are welcome to take a stab at issues marked with this label.',
            },
            {
                id: 2828369804,
                node_id: 'MDU6TGFiZWwyODI4MzY5ODA0',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/GFI_Climate_Action_SIG',
                name: 'GFI_Climate_Action_SIG',
                color: '6923EE',
                default: false,
                description:
                    'Good first issues, specific to our effort to help the Climate Action and Accounting SIG.',
            },
            {
                id: 2924324338,
                node_id: 'MDU6TGFiZWwyOTI0MzI0MzM4',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue-400-expert',
                name: 'good-first-issue-400-expert',
                color: 'DF3D22',
                default: false,
                description: '',
            },
        ],
        assignees: 0,
        comments: 2,
        created_at: '2021-04-24T21:57:59Z',
    },
    {
        issues: 'https://api.github.com/repos/hyperledger/cacti/issues/238',
        title: 'test: migrate from test runner tap to jest',
        body: '### Update 2021-08-09\r\n\r\nThis used to be about AVA but now is about Jest\r\n\r\n### Update 2020-11-02\r\n\r\nSwitched the target to AVA from jest, details below in comments.\r\n\r\n### Description\r\nAs a developer I want to be able to write unit tests for the universal packages that execute the same code both in NodeJS and in the browser so that I don\'t have to duplicate work in order to have test coverage for both platforms for the cross-platform packages.\r\n\r\nWhile working on the stable signature generation, we\'ve discovered that accidentally the wrong library was used initially (congratulations to Peter) which is called "tap" instead of "tape". They both do the same thing (test runners for TAP - `Test Anything Protocol`) but the `tap` library does not work in browsers while the `tape` library is, so to keep the build/test infrastructure of the project as simple as possible it would be the best to migrate to `tape` entirely since it anyway has support for `TAP` (the protocol)\r\n\r\nhttps://www.npmjs.com/package/ava\r\n\r\n### Acceptance Criteria\r\n1. Complexity of build/test scripts has not increased\r\n2. Tests for cross-platform packages such as `cactus-common` can be written once and ran "anywhere" (NodeJS, browser)\r\n3. Developer workflow has not lengthened, did not increase in complexity (from the human perspective, not code-wise that was mentioned in 1))\r\n\r\ncc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton @AzaharaC @jordigiam @kikoncuo',
        labels: [
            {
                id: 1629728751,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzUx',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/bug',
                name: 'bug',
                color: 'd73a4a',
                default: true,
                description: "Something isn't working",
            },
            {
                id: 1629728757,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzU3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue',
                name: 'good-first-issue',
                color: '7057ff',
                default: false,
                description: 'Good for newcomers',
            },
            {
                id: 1657071350,
                node_id: 'MDU6TGFiZWwxNjU3MDcxMzUw',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Nice-to-Have',
                name: 'Nice-to-Have',
                color: '5ea0bc',
                default: false,
                description: '',
            },
            {
                id: 1762140891,
                node_id: 'MDU6TGFiZWwxNzYyMTQwODkx',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/dependencies',
                name: 'dependencies',
                color: '0366d6',
                default: false,
                description: 'Pull requests that update a dependency file',
            },
            {
                id: 2411211154,
                node_id: 'MDU6TGFiZWwyNDExMjExMTU0',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Hacktoberfest',
                name: 'Hacktoberfest',
                color: '9bc6f2',
                default: false,
                description:
                    'Hacktoberfest participants are welcome to take a stab at issues marked with this label.',
            },
            {
                id: 2924323155,
                node_id: 'MDU6TGFiZWwyOTI0MzIzMTU1',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue-200-intermediate',
                name: 'good-first-issue-200-intermediate',
                color: '8A9642',
                default: false,
                description: '',
            },
            {
                id: 3475004911,
                node_id: 'LA_kwDODOk1Zs7PIF3v',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Tests',
                name: 'Tests',
                color: '1d76db',
                default: false,
                description:
                    'Anything related to tests be that automatic or manual, integration or unit, etc.',
            },
            {
                id: 3515617514,
                node_id: 'LA_kwDODOk1Zs7RjBDq',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/P4',
                name: 'P4',
                color: '1D76DB',
                default: false,
                description: 'Priority 4: Low',
            },
            {
                id: 5770656692,
                node_id: 'LA_kwDODOk1Zs8AAAABV_U7tA',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/backlog',
                name: 'backlog',
                color: '56552D',
                default: false,
                description:
                    'Tasks that are needed but we cannot prioritize them at present.',
            },
        ],
        assignees: 0,
        comments: 5,
        created_at: '2020-07-24T02:58:54Z',
    },
];
