export const frontendIssues = [
    {
        issues: 'https://api.github.com/repos/hyperledger/cacti/issues/1715',
        title: 'build(deps): upgrade to TS 4.4 supply-chain-frontend',
        body: null,
        labels: [
            {
                id: 1629728757,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzU3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue',
                name: 'good-first-issue',
                color: '7057ff',
                default: false,
                description: 'Good for newcomers',
            },
            {
                id: 1657071350,
                node_id: 'MDU6TGFiZWwxNjU3MDcxMzUw',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Nice-to-Have',
                name: 'Nice-to-Have',
                color: '5ea0bc',
                default: false,
                description: '',
            },
            {
                id: 1762140891,
                node_id: 'MDU6TGFiZWwxNzYyMTQwODkx',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/dependencies',
                name: 'dependencies',
                color: '0366d6',
                default: false,
                description: 'Pull requests that update a dependency file',
            },
            {
                id: 2092205837,
                node_id: 'MDU6TGFiZWwyMDkyMjA1ODM3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Developer_Experience',
                name: 'Developer_Experience',
                color: '5319e7',
                default: false,
                description: '',
            },
            {
                id: 2411211154,
                node_id: 'MDU6TGFiZWwyNDExMjExMTU0',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Hacktoberfest',
                name: 'Hacktoberfest',
                color: '9bc6f2',
                default: false,
                description:
                    'Hacktoberfest participants are welcome to take a stab at issues marked with this label.',
            },
            {
                id: 2924323155,
                node_id: 'MDU6TGFiZWwyOTI0MzIzMTU1',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue-200-intermediate',
                name: 'good-first-issue-200-intermediate',
                color: '8A9642',
                default: false,
                description: '',
            },
            {
                id: 3515617514,
                node_id: 'LA_kwDODOk1Zs7RjBDq',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/P4',
                name: 'P4',
                color: '1D76DB',
                default: false,
                description: 'Priority 4: Low',
            },
        ],
        assignees: 1,
        comments: 0,
        created_at: '2022-01-10T21:21:54Z',
    },
    {
        issues: 'https://api.github.com/repos/hyperledger/cacti/issues/1712',
        title: 'build(deps): upgrade to TS 4.4 carbon-accounting-frontend',
        body: null,
        labels: [
            {
                id: 1629728757,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzU3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue',
                name: 'good-first-issue',
                color: '7057ff',
                default: false,
                description: 'Good for newcomers',
            },
            {
                id: 1657071350,
                node_id: 'MDU6TGFiZWwxNjU3MDcxMzUw',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Nice-to-Have',
                name: 'Nice-to-Have',
                color: '5ea0bc',
                default: false,
                description: '',
            },
            {
                id: 1762140891,
                node_id: 'MDU6TGFiZWwxNzYyMTQwODkx',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/dependencies',
                name: 'dependencies',
                color: '0366d6',
                default: false,
                description: 'Pull requests that update a dependency file',
            },
            {
                id: 2092205837,
                node_id: 'MDU6TGFiZWwyMDkyMjA1ODM3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Developer_Experience',
                name: 'Developer_Experience',
                color: '5319e7',
                default: false,
                description: '',
            },
            {
                id: 2411211154,
                node_id: 'MDU6TGFiZWwyNDExMjExMTU0',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Hacktoberfest',
                name: 'Hacktoberfest',
                color: '9bc6f2',
                default: false,
                description:
                    'Hacktoberfest participants are welcome to take a stab at issues marked with this label.',
            },
            {
                id: 2924323155,
                node_id: 'MDU6TGFiZWwyOTI0MzIzMTU1',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue-200-intermediate',
                name: 'good-first-issue-200-intermediate',
                color: '8A9642',
                default: false,
                description: '',
            },
            {
                id: 3515617514,
                node_id: 'LA_kwDODOk1Zs7RjBDq',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/P4',
                name: 'P4',
                color: '1D76DB',
                default: false,
                description: 'Priority 4: Low',
            },
        ],
        assignees: 1,
        comments: 0,
        created_at: '2022-01-10T21:21:35Z',
    },
    {
        issues: 'https://api.github.com/repos/hyperledger/cacti/issues/1129',
        title: 'build(deps): upgrade to Typescript v4.4',
        body: "### Description\n\nCurrently we use tsc 4.3.x or similar but 4.4 is now in public beta[1] and have a couple of  very cool features that we want to start using as soon as possible to increase code quality in the project.\n\n[1]: https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-beta/\n\nSpecifically want to leverage this[2] feature which should make it so that if `Checks.truthy(...)` was used to assert that something is truthy, then in the following line the compiler will recognize this at compile time (which it hasn't done so before)\n\n[2]: https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-beta/#cfa-aliased-conditions\n\n### Acceptance Criteria\n1. Wait until 4.4 comes out of beta (but we can start testing today so that as soon as it hits GA, we can pull the plug with the upgrade)\n1. The Typescript compiler dependency is updated to 4.4\n2. CI is passing still\n\n```sh\n$ yarn lerna ls\nyarn run v1.18.0\nlerna notice cli v4.0.0\n@hyperledger/cactus-example-carbon-accounting-backend\n@hyperledger/cactus-example-carbon-accounting-business-logic-plugin\n@hyperledger/cactus-example-carbon-accounting-frontend\n@hyperledger/cactus-example-supply-chain-backend\n@hyperledger/cactus-example-supply-chain-business-logic-plugin\n@hyperledger/cactus-example-supply-chain-frontend\n@hyperledger/cactus-plugin-htlc-coordinator-besu\n@hyperledger/cactus-plugin-object-store-ipfs\n@hyperledger/cactus-api-client\n@hyperledger/cactus-cmd-api-server\n@hyperledger/cactus-common\n@hyperledger/cactus-core-api\n@hyperledger/cactus-core\n@hyperledger/cactus-plugin-consortium-manual\n@hyperledger/cactus-plugin-htlc-eth-besu-erc20\n@hyperledger/cactus-plugin-htlc-eth-besu\n@hyperledger/cactus-plugin-keychain-aws-sm\n@hyperledger/cactus-plugin-keychain-azure-kv\n@hyperledger/cactus-plugin-keychain-google-sm\n@hyperledger/cactus-plugin-keychain-memory-wasm\n@hyperledger/cactus-plugin-keychain-memory\n@hyperledger/cactus-plugin-keychain-vault\n@hyperledger/cactus-plugin-ledger-connector-besu\n@hyperledger/cactus-plugin-ledger-connector-corda\n@hyperledger/cactus-plugin-ledger-connector-fabric-socketio\n@hyperledger/cactus-plugin-ledger-connector-fabric\n@hyperledger/cactus-plugin-ledger-connector-go-ethereum-socketio\n@hyperledger/cactus-plugin-ledger-connector-iroha\n@hyperledger/cactus-plugin-ledger-connector-quorum\n@hyperledger/cactus-plugin-ledger-connector-sawtooth-socketio\n@hyperledger/cactus-plugin-ledger-connector-xdai\n@hyperledger/cactus-plugin-odap-hermes\n@hyperledger/cactus-test-api-client\n@hyperledger/cactus-test-cmd-api-server\n@hyperledger/cactus-test-plugin-consortium-manual\n@hyperledger/cactus-test-plugin-htlc-eth-besu-erc20\n@hyperledger/cactus-test-plugin-htlc-eth-besu\n@hyperledger/cactus-test-plugin-ledger-connector-besu\n@hyperledger/cactus-test-plugin-ledger-connector-quorum\n@hyperledger/cactus-test-tooling\nlerna success found 40 packages\nDone in 1.02s.\n```\n\ncc: @ty-lazar @Jeff-Ushry @twiggins120 @awadhana @Leeyoungone",
        labels: [
            {
                id: 1629728757,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzU3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue',
                name: 'good-first-issue',
                color: '7057ff',
                default: false,
                description: 'Good for newcomers',
            },
            {
                id: 1657071350,
                node_id: 'MDU6TGFiZWwxNjU3MDcxMzUw',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Nice-to-Have',
                name: 'Nice-to-Have',
                color: '5ea0bc',
                default: false,
                description: '',
            },
            {
                id: 1762140891,
                node_id: 'MDU6TGFiZWwxNzYyMTQwODkx',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/dependencies',
                name: 'dependencies',
                color: '0366d6',
                default: false,
                description: 'Pull requests that update a dependency file',
            },
            {
                id: 2092205837,
                node_id: 'MDU6TGFiZWwyMDkyMjA1ODM3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Developer_Experience',
                name: 'Developer_Experience',
                color: '5319e7',
                default: false,
                description: '',
            },
            {
                id: 2411211154,
                node_id: 'MDU6TGFiZWwyNDExMjExMTU0',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Hacktoberfest',
                name: 'Hacktoberfest',
                color: '9bc6f2',
                default: false,
                description:
                    'Hacktoberfest participants are welcome to take a stab at issues marked with this label.',
            },
            {
                id: 2727659927,
                node_id: 'MDU6TGFiZWwyNzI3NjU5OTI3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Epic',
                name: 'Epic',
                color: '3E4B9E',
                default: false,
                description: null,
            },
            {
                id: 2924323155,
                node_id: 'MDU6TGFiZWwyOTI0MzIzMTU1',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue-200-intermediate',
                name: 'good-first-issue-200-intermediate',
                color: '8A9642',
                default: false,
                description: '',
            },
        ],
        assignees: 1,
        comments: 1,
        created_at: '2021-07-13T21:05:19Z',
    },
    {
        issues: 'https://api.github.com/repos/hyperledger/cacti/issues/650',
        title: 'test(examples): puppeteer GUI tests for supply chain frontend',
        body: '### Description\n\nAs a contributor I want to be able to change **any** part of the code and have at least some level of confidence that my chance will be touched upon by some tests at least partially.\nCurrently this is not the case. For example when dependencies were removed by an automated tool, certain errors could be introduced that would only surface if a human actually tried to run the examples that have web GUIs (the CI kept happily passing despite the issues).\n\nPuppeteer is a great tool to run a headless chrome instance and have it scrape Angular/Ionic apps.\nA case could be made to have Protractor in the loop on top as well (which is what Angular uses out of the box anyway).\n\n### Acceptance Criteria\n1. Use either Puppeteer or Protractor to have end to end GUI tests actually verify the examples as part of the CI\n2. Have the mentioned tests passing.\n3. Also include at least some minimal testing the same way for the `./packages/cactus-cockpit` as well.\n\ncc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton @AzaharaC @jordigiam @kikoncuo',
        labels: [
            {
                id: 1629728755,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzU1',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/enhancement',
                name: 'enhancement',
                color: 'a2eeef',
                default: true,
                description: 'New feature or request',
            },
            {
                id: 1629728757,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzU3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue',
                name: 'good-first-issue',
                color: '7057ff',
                default: false,
                description: 'Good for newcomers',
            },
            {
                id: 1657071350,
                node_id: 'MDU6TGFiZWwxNjU3MDcxMzUw',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Nice-to-Have',
                name: 'Nice-to-Have',
                color: '5ea0bc',
                default: false,
                description: '',
            },
            {
                id: 1762140891,
                node_id: 'MDU6TGFiZWwxNzYyMTQwODkx',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/dependencies',
                name: 'dependencies',
                color: '0366d6',
                default: false,
                description: 'Pull requests that update a dependency file',
            },
            {
                id: 2092205837,
                node_id: 'MDU6TGFiZWwyMDkyMjA1ODM3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Developer_Experience',
                name: 'Developer_Experience',
                color: '5319e7',
                default: false,
                description: '',
            },
            {
                id: 2411211154,
                node_id: 'MDU6TGFiZWwyNDExMjExMTU0',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Hacktoberfest',
                name: 'Hacktoberfest',
                color: '9bc6f2',
                default: false,
                description:
                    'Hacktoberfest participants are welcome to take a stab at issues marked with this label.',
            },
            {
                id: 2924323587,
                node_id: 'MDU6TGFiZWwyOTI0MzIzNTg3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue-300-advanced',
                name: 'good-first-issue-300-advanced',
                color: 'D65806',
                default: false,
                description: '',
            },
        ],
        assignees: 0,
        comments: 0,
        created_at: '2021-03-10T08:49:46Z',
    },
    {
        issues: 'https://api.github.com/repos/Umuzi-org/ACN-syllabus/issues/18',
        title: 'topics/web-frontend/browser-based-storage add a bit of text ',
        body: 'Students should be curious about clicking the link. Add some text\r\n\r\nAre there any other tutorials or resources that would make this topic better?  ',
        labels: [
            {
                id: 2394110766,
                node_id: 'MDU6TGFiZWwyMzk0MTEwNzY2',
                url: 'https://api.github.com/repos/Umuzi-org/ACN-syllabus/labels/hacktoberfest',
                name: 'hacktoberfest',
                color: '5319e7',
                default: false,
                description: '',
            },
            {
                id: 2400793684,
                node_id: 'MDU6TGFiZWwyNDAwNzkzNjg0',
                url: 'https://api.github.com/repos/Umuzi-org/ACN-syllabus/labels/good-first-issue',
                name: 'good-first-issue',
                color: '29bc9f',
                default: false,
                description: '',
            },
            {
                id: 2400794105,
                node_id: 'MDU6TGFiZWwyNDAwNzk0MTA1',
                url: 'https://api.github.com/repos/Umuzi-org/ACN-syllabus/labels/status/claimed',
                name: 'status/claimed',
                color: '9bc645',
                default: false,
                description: '',
            },
        ],
        assignees: 0,
        comments: 1,
        created_at: '2020-10-02T09:57:12Z',
    },
    {
        issues: 'https://api.github.com/repos/schedutron/home-server/issues/15',
        title: 'Add likes counter for videos',
        body: 'Will require enhancing both the front-end and the Flask back-end.',
        labels: [
            {
                id: 670324136,
                node_id: 'MDU6TGFiZWw2NzAzMjQxMzY=',
                url: 'https://api.github.com/repos/schedutron/home-server/labels/enhancement',
                name: 'enhancement',
                color: '84b6eb',
                default: true,
                description: null,
            },
            {
                id: 670324137,
                node_id: 'MDU6TGFiZWw2NzAzMjQxMzc=',
                url: 'https://api.github.com/repos/schedutron/home-server/labels/help%20wanted',
                name: 'help wanted',
                color: '128A0C',
                default: true,
                description: null,
            },
            {
                id: 733654543,
                node_id: 'MDU6TGFiZWw3MzM2NTQ1NDM=',
                url: 'https://api.github.com/repos/schedutron/home-server/labels/hacktoberfest',
                name: 'hacktoberfest',
                color: '9d7ccc',
                default: false,
                description: null,
            },
            {
                id: 733860832,
                node_id: 'MDU6TGFiZWw3MzM4NjA4MzI=',
                url: 'https://api.github.com/repos/schedutron/home-server/labels/good-first-issue',
                name: 'good-first-issue',
                color: '61e843',
                default: false,
                description: null,
            },
        ],
        assignees: 0,
        comments: 4,
        created_at: '2017-10-29T06:44:28Z',
    },
];
