export const reactIssues = [
    {
        issues: 'https://api.github.com/repos/aws-powertools/powertools-lambda-typescript/issues/1740',
        title: 'Maintenance: initialize AWS SDK client only when needed to improve performance in Parameters',
        body: "### Summary\n\nHello,\r\nI am currently doing some performance tuning in our lambda functions and i notice that getting SSM parameters introduce some latency in the first execution. I've executed tests using both the getParameter utility and also SSMProvider. These were my findings:\r\nssm client instantiation: ~50ms\r\nssm provider instantiation: ~50ms\r\ngetParameter: 380ms (discounting 300ms from SDK, ~80ms) \r\nSSM SDK get parameter: 300ms\r\n\r\nIn my tests I've used lambda functions configured with provisioned concurrency, so I tried to bring some of the latency to the INIT phase. I understand the best way to do it would be to:\r\n1) Instantiante the SSM client in the static scope, maybe using a capture to trace this call\r\n2) Passing the client to SSMProvider\r\n3) Using SSMProvider instead of getParameter utility, which would add the latency of instantiating a SSM client inside the handler code.\r\n\r\nHowever, I haven't noticed any gain of doing that. By inspecting the code bellow, I've noticed that SSM client is instantiated even when it's not used, i.e., when one passes the client as parameter. I believe this section could be optimized so that SSM client is only instantiated if none is available:\r\n\r\n```\r\n/**\r\n   * It initializes the SSMProvider class.\r\n   *\r\n   * @param {SSMProviderOptions} config - The configuration object.\r\n   */\r\n  public constructor(config?: SSMProviderOptions) {\r\n    super();\r\n\r\n    this.client = new SSMClient(config?.clientConfig || {});\r\n    if (config?.awsSdkV3Client) {\r\n      if (isSdkClient(config.awsSdkV3Client)) {\r\n        this.client = config.awsSdkV3Client;\r\n      } else {\r\n        console.warn(\r\n          'awsSdkV3Client is not an AWS SDK v3 client, using default client'\r\n        );\r\n      }\r\n    }\r\n    addUserAgentMiddleware(this.client, 'parameters');\r\n  }\r\n``` \n\n### Why is this needed?\n\nImprove performance of first execution when SSMProvider has a SSM client.\n\n### Which area does this relate to?\n\nParameters\n\n### Solution\n\nInstantiate SSM client only when none is available\n\n### Acknowledgment\n\n- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)\n- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)\n\n### Future readers\n\nPlease react with \ud83d\udc4d and your use case to help us understand customer demand.",
        labels: [
            {
                id: 2438946361,
                node_id: 'MDU6TGFiZWwyNDM4OTQ2MzYx',
                url: 'https://api.github.com/repos/aws-powertools/powertools-lambda-typescript/labels/good-first-issue',
                name: 'good-first-issue',
                color: '7057ff',
                default: false,
                description:
                    'Something that is suitable for those who want to start contributing',
            },
            {
                id: 2438946363,
                node_id: 'MDU6TGFiZWwyNDM4OTQ2MzYz',
                url: 'https://api.github.com/repos/aws-powertools/powertools-lambda-typescript/labels/help-wanted',
                name: 'help-wanted',
                color: '008672',
                default: false,
                description:
                    'We would really appreciate some support from community for this one',
            },
            {
                id: 4349329821,
                node_id: 'LA_kwDOEjWUk88AAAABAz2BnQ',
                url: 'https://api.github.com/repos/aws-powertools/powertools-lambda-typescript/labels/area/parameters',
                name: 'area/parameters',
                color: 'F779DC',
                default: false,
                description: 'This item relates to the Parameters Utility',
            },
            {
                id: 4794878416,
                node_id: 'LA_kwDOEjWUk88AAAABHcwJ0A',
                url: 'https://api.github.com/repos/aws-powertools/powertools-lambda-typescript/labels/status/confirmed',
                name: 'status/confirmed',
                color: '4FEECD',
                default: false,
                description: 'The scope is clear, ready for implementation',
            },
            {
                id: 6034271306,
                node_id: 'LA_kwDOEjWUk88AAAABZ6usSg',
                url: 'https://api.github.com/repos/aws-powertools/powertools-lambda-typescript/labels/hacktoberfest',
                name: 'hacktoberfest',
                color: 'ADDE32',
                default: false,
                description: '',
            },
        ],
        assignees: 0,
        comments: 3,
        created_at: '2023-10-12T14:04:51Z',
    },
    {
        issues: 'https://api.github.com/repos/aws-powertools/powertools-lambda-typescript/issues/1729',
        title: 'Maintenance: refactor `Logger` types and interfaces to improve consistency and clarity',
        body: '### Summary\n\nReview all type and interface definitions and usage throughout the codebase to identify opportunities for refactoring and clean up. This will help improve consistency in naming, structure, and usage of types across the project. \r\n\r\nSpecific areas to investigate:\r\n\r\n- Inconsistent naming (plural vs singular, capitalization, abbreviations, etc.)\r\n- Misnamed types that are not actually types but constants or enums\r\n- Usage of `any` where more specific types could be defined\r\n- Opportunities to convert usage of enums to `as const` types\r\n- Inheritance hierarchies that could be simplified\r\n- Re-organization of types into more logical modules/namespaces\n\n### Why is this needed?\n\nAs the project has grown organically, inconsistencies in how types are defined and used have emerged. By refactoring and cleaning these up, we can improve maintainability, clarity, and reliability of the codebase.\r\n\r\nMore consistent and intention-revealing names will also improve onboarding and comprehension as well as DX.\r\n\r\nConverting usage to proper types where applicable will enable stronger compiler checking and editor tooling support. Overall, this refactoring will leave the code in better shape for continued development and maintenance.\n\n### Which area does this relate to?\n\n_No response_\n\n### Solution\n\nExamples of types/interfaces/objects that could be improved:\r\n- `ClassThatLogs` ([here](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/packages/logger/src/types/Logger.ts#L16)) might be converted to an interface, renamed, and made to include all methods\r\n- `ConstructorOptions` ([here](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/packages/logger/src/types/Logger.ts#L28)) could be renamed to something more explanatory like `LoggerOptions` or similar (check other utilities)\r\n- `LogJsonIndent` ([here](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/packages/logger/src/types/Logger.ts#L92)) should be moved out of this file and into a `constants.ts` file similar to what done in other utilities, also it should be converted to an object as we are moving away from enums.\r\n\r\n----\r\n\r\n> [!important]\r\n> Before starting to work on a PR for this issue, the assignee should do an investigation of the code and propose an action plan under this issue. \r\n> \r\n> Once the plan has been discussed and agreed upon with at least one maintainer work on the PR can start.\n\n### Acknowledgment\n\n- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda-typescript/latest/#tenets)\n- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)\n\n### Future readers\n\nPlease react with \ud83d\udc4d and your use case to help us understand customer demand.',
        labels: [
            {
                id: 2438946361,
                node_id: 'MDU6TGFiZWwyNDM4OTQ2MzYx',
                url: 'https://api.github.com/repos/aws-powertools/powertools-lambda-typescript/labels/good-first-issue',
                name: 'good-first-issue',
                color: '7057ff',
                default: false,
                description:
                    'Something that is suitable for those who want to start contributing',
            },
            {
                id: 2438946363,
                node_id: 'MDU6TGFiZWwyNDM4OTQ2MzYz',
                url: 'https://api.github.com/repos/aws-powertools/powertools-lambda-typescript/labels/help-wanted',
                name: 'help-wanted',
                color: '008672',
                default: false,
                description:
                    'We would really appreciate some support from community for this one',
            },
            {
                id: 2816371619,
                node_id: 'MDU6TGFiZWwyODE2MzcxNjE5',
                url: 'https://api.github.com/repos/aws-powertools/powertools-lambda-typescript/labels/area/logger',
                name: 'area/logger',
                color: '0E4EDC',
                default: false,
                description: 'This item relates to the Logger Utility',
            },
            {
                id: 4794877697,
                node_id: 'LA_kwDOEjWUk88AAAABHcwHAQ',
                url: 'https://api.github.com/repos/aws-powertools/powertools-lambda-typescript/labels/status/discussing',
                name: 'status/discussing',
                color: '895B69',
                default: false,
                description:
                    'The issue needs to be discussed, elaborated, or refined',
            },
            {
                id: 6034271306,
                node_id: 'LA_kwDOEjWUk88AAAABZ6usSg',
                url: 'https://api.github.com/repos/aws-powertools/powertools-lambda-typescript/labels/hacktoberfest',
                name: 'hacktoberfest',
                color: 'ADDE32',
                default: false,
                description: '',
            },
        ],
        assignees: 0,
        comments: 2,
        created_at: '2023-10-02T17:56:44Z',
    },
    {
        issues: 'https://api.github.com/repos/Axe-Pearl/Articles/issues/1',
        title: 'Write a Detailed and well explained Article on JavaScript Async and Await',
        body: '**Issue is open for all**\r\n\r\nRefer to this Article for help -\r\n https://www.freecodecamp.org/news/javascript-async-await-tutorial-learn-callbacks-promises-async-await-by-making-icecream/\r\n\r\nFollow these steps - \r\n1. Star the Repository\r\n2. Write an Article\r\n3. Make a pull request \r\n4. I will merge your pull request\r\n \r\n**NOTE:** Remember that you put the Article in the Respective Directory ->\r\nhttps://github.com/Axe-Pearl/Articles-Hacktoberfest/tree/master/JavaScript/Async-Await\r\n---- -----\r\nFor more such issues and to get notified first, follow me on \r\nGitHub - https://github.com/Axe-Pearl\r\nInstagram - https://www.instagram.com/anurag_nema_ytube/\r\n\r\nAlso, Subscribe to our YouTube Channel where we talk about coding concepts, building amazing kinds of stuff,  tips and tricks, and much more - \r\nhttps://www.youtube.com/channel/UC8uVulieEYQWms4Jf8uxQ2g\r\n---- ----',
        labels: [
            {
                id: 4609526302,
                node_id: 'LA_kwDOIHyDAs8AAAABEr_KHg',
                url: 'https://api.github.com/repos/Axe-Pearl/Articles/labels/documentation',
                name: 'documentation',
                color: '0075ca',
                default: true,
                description: 'Improvements or additions to documentation',
            },
            {
                id: 4609526334,
                node_id: 'LA_kwDOIHyDAs8AAAABEr_KPg',
                url: 'https://api.github.com/repos/Axe-Pearl/Articles/labels/good%20first%20issue',
                name: 'good first issue',
                color: '7057ff',
                default: true,
                description: 'Good for newcomers',
            },
            {
                id: 4609540030,
                node_id: 'LA_kwDOIHyDAs8AAAABEr__vg',
                url: 'https://api.github.com/repos/Axe-Pearl/Articles/labels/beginner',
                name: 'beginner',
                color: '0e8a16',
                default: false,
                description: '',
            },
            {
                id: 4609542010,
                node_id: 'LA_kwDOIHyDAs8AAAABEsAHeg',
                url: 'https://api.github.com/repos/Axe-Pearl/Articles/labels/beginner-friendly',
                name: 'beginner-friendly',
                color: '96B8D9',
                default: false,
                description: '',
            },
            {
                id: 4609543352,
                node_id: 'LA_kwDOIHyDAs8AAAABEsAMuA',
                url: 'https://api.github.com/repos/Axe-Pearl/Articles/labels/HACKTOBERFEST-ACCEPTED',
                name: 'HACKTOBERFEST-ACCEPTED',
                color: '0CB763',
                default: false,
                description: '',
            },
            {
                id: 4609544183,
                node_id: 'LA_kwDOIHyDAs8AAAABEsAP9w',
                url: 'https://api.github.com/repos/Axe-Pearl/Articles/labels/hacktoberfest',
                name: 'hacktoberfest',
                color: '443621',
                default: false,
                description: '',
            },
            {
                id: 4609545350,
                node_id: 'LA_kwDOIHyDAs8AAAABEsAUhg',
                url: 'https://api.github.com/repos/Axe-Pearl/Articles/labels/first-timers',
                name: 'first-timers',
                color: 'ED360A',
                default: false,
                description: '',
            },
            {
                id: 4609547914,
                node_id: 'LA_kwDOIHyDAs8AAAABEsAeig',
                url: 'https://api.github.com/repos/Axe-Pearl/Articles/labels/good-first-issue',
                name: 'good-first-issue',
                color: '03F9DC',
                default: false,
                description: '',
            },
            {
                id: 4609549234,
                node_id: 'LA_kwDOIHyDAs8AAAABEsAjsg',
                url: 'https://api.github.com/repos/Axe-Pearl/Articles/labels/javascript',
                name: 'javascript',
                color: '8389A3',
                default: false,
                description: '',
            },
            {
                id: 4609550501,
                node_id: 'LA_kwDOIHyDAs8AAAABEsAopQ',
                url: 'https://api.github.com/repos/Axe-Pearl/Articles/labels/first-contribution',
                name: 'first-contribution',
                color: '2681E0',
                default: false,
                description: '',
            },
            {
                id: 4609553428,
                node_id: 'LA_kwDOIHyDAs8AAAABEsA0FA',
                url: 'https://api.github.com/repos/Axe-Pearl/Articles/labels/Article',
                name: 'Article',
                color: '113FD0',
                default: false,
                description: '',
            },
            {
                id: 4609555965,
                node_id: 'LA_kwDOIHyDAs8AAAABEsA9_Q',
                url: 'https://api.github.com/repos/Axe-Pearl/Articles/labels/Blog',
                name: 'Blog',
                color: 'A5C10B',
                default: false,
                description: '',
            },
        ],
        assignees: 5,
        comments: 11,
        created_at: '2022-10-03T17:23:10Z',
    },
    {
        issues: 'https://api.github.com/repos/Swati4star/Calculator-React/issues/2',
        title: 'Add JavaScript tests',
        body: 'Add JavaScript tests\r\n\r\nReference : https://facebook.github.io/react-native/docs/testing.html#javascript',
        labels: [
            {
                id: 480593334,
                node_id: 'MDU6TGFiZWw0ODA1OTMzMzQ=',
                url: 'https://api.github.com/repos/Swati4star/Calculator-React/labels/enhancement',
                name: 'enhancement',
                color: '84b6eb',
                default: true,
                description: null,
            },
            {
                id: 734146792,
                node_id: 'MDU6TGFiZWw3MzQxNDY3OTI=',
                url: 'https://api.github.com/repos/Swati4star/Calculator-React/labels/hacktoberfest',
                name: 'hacktoberfest',
                color: 'fcbdd8',
                default: false,
                description: null,
            },
            {
                id: 734146921,
                node_id: 'MDU6TGFiZWw3MzQxNDY5MjE=',
                url: 'https://api.github.com/repos/Swati4star/Calculator-React/labels/good-first-issue',
                name: 'good-first-issue',
                color: 'd6cf00',
                default: false,
                description: null,
            },
        ],
        assignees: 0,
        comments: 3,
        created_at: '2017-10-29T07:19:26Z',
    },
];
