export const technicalWritingIssues = [
    {
        issues: 'https://api.github.com/repos/hyperledger/cacti/issues/2762',
        title: 'fix(connector-quorum/weaver): remove/encrypt sensitive data',
        body: '## Description\r\nStatic source code assessment has picked up a potential vulnerability regarding exposure of secrets. The potential fix is to log the non-sensitive information instead (like the key for the secret) or remove it all together if its not necessary.\r\n\r\n## The report from which the above information was summarized\r\nRisk Rating: Medium\r\nCategory: Sensitive data exposure\r\n\r\n### Description\r\nThe application sends user information, such as passwords, outside the application, such as writing it to a local text or log file or sending it to an external web service.\r\n\r\n### Impact\r\nA user\u2019s personal information could be stolen by a malicious programmer, or an attacker that intercepts the data.\r\n\r\n### Remediation Recommendation\r\n\u2022 Personal data should be removed before writing to logs or other files.\r\n\u2022 Review the need, justification of sending personal data to remote web services.\r\n\u2022 Encrypt the sensitive information before it is displayed\r\n\r\n### Affected files (path - line number)\r\n\r\nweaver/core/identity-management/iin-agent/src/fabric-ledger/networkUtils.ts - 36\r\nweaver/core/identity-management/iin-agent/src/fabric-ledger /walletUtils.ts - 37\r\npackages/cactus-plugin-ledger-connector-quorum/src/scripts/get-quorum-connector-status.ts - 111\r\n\r\n## Snapshot of the sourcecode at the time of scan\r\n\r\n<img width="686" alt="image" src="https://github.com/hyperledger/cacti/assets/56861721/48793910-150f-4f67-b72d-49e86ff75e7c">\r\n<img width="675" alt="image" src="https://github.com/hyperledger/cacti/assets/56861721/d8de1bc8-4986-4221-9ea7-779484d0756c">\r\n\r\n---\r\n\r\nSource: `APP PE Hyperledger Cacti v2.0.0 - Static Application Assessment Report.odt`\r\n\r\ncc: @takeutak @izuru0 @outSH @petermetz ',
        labels: [
            {
                id: 1629728757,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzU3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue',
                name: 'good-first-issue',
                color: '7057ff',
                default: false,
                description: 'Good for newcomers',
            },
            {
                id: 1657286373,
                node_id: 'MDU6TGFiZWwxNjU3Mjg2Mzcz',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Quorum',
                name: 'Quorum',
                color: '017f51',
                default: false,
                description: '',
            },
            {
                id: 2085827790,
                node_id: 'MDU6TGFiZWwyMDg1ODI3Nzkw',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Security',
                name: 'Security',
                color: 'FF0000',
                default: false,
                description:
                    'Related to existing or potential security vulnerabilities',
            },
            {
                id: 2411211154,
                node_id: 'MDU6TGFiZWwyNDExMjExMTU0',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Hacktoberfest',
                name: 'Hacktoberfest',
                color: '9bc6f2',
                default: false,
                description:
                    'Hacktoberfest participants are welcome to take a stab at issues marked with this label.',
            },
            {
                id: 3515616541,
                node_id: 'LA_kwDODOk1Zs7RjA0d',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/P3',
                name: 'P3',
                color: 'FBCA04',
                default: false,
                description: 'Priority 3: Medium',
            },
            {
                id: 3531600086,
                node_id: 'LA_kwDODOk1Zs7Sf_DW',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Weaver',
                name: 'Weaver',
                color: '7CEC52',
                default: false,
                description:
                    'Tasks related to the future of Cactus & Weaver together.',
            },
        ],
        assignees: 0,
        comments: 0,
        created_at: '2023-10-11T07:57:27Z',
    },
    {
        issues: 'https://api.github.com/repos/openwisp/openwisp-radius/issues/467',
        title: '[bug] FreeRADIUS PostAuthView returns 500 error ',
        body: 'The FreeRADIUS PostAuthView (`/api/v1/freeradius/postauth/`) returns HTTP 500 error if the length of `called_station_id` field exceeds 50 characters. \r\n\r\nA possible fix could be to update the PostAuthSerializer and set `max_length` attribute on the `called_station_id` field. This way, the view would return HTTP 400 with the error reason. \r\n\r\n\r\n',
        labels: [
            {
                id: 1015803038,
                node_id: 'MDU6TGFiZWwxMDE1ODAzMDM4',
                url: 'https://api.github.com/repos/openwisp/openwisp-radius/labels/bug',
                name: 'bug',
                color: 'd73a4a',
                default: true,
                description: "Something isn't working",
            },
            {
                id: 1015803042,
                node_id: 'MDU6TGFiZWwxMDE1ODAzMDQy',
                url: 'https://api.github.com/repos/openwisp/openwisp-radius/labels/good-first-issue',
                name: 'good-first-issue',
                color: '7057ff',
                default: false,
                description: 'Good for newcomers',
            },
            {
                id: 2368867475,
                node_id: 'MDU6TGFiZWwyMzY4ODY3NDc1',
                url: 'https://api.github.com/repos/openwisp/openwisp-radius/labels/Hacktoberfest',
                name: 'Hacktoberfest',
                color: 'fb87dd',
                default: false,
                description:
                    'Easy issues for attracting Hacktoberfest participants.',
            },
        ],
        assignees: 0,
        comments: 2,
        created_at: '2023-01-11T12:02:31Z',
    },
    {
        issues: 'https://api.github.com/repos/allegro/axion-release-plugin/issues/500',
        title: 'KotlinDSL preRelease fileUpdate cannot be cast to groovy.lang.Closure',
        body: 'Hi, \r\nInspired to using Kotlin DSL and the recent additions to the plugin I started using the new Kotlin DSL methods. They seem to work except for fileUpdate. I considered writing this in #449 , however since it\'s released I decided this might be better reported on its own.\r\n\r\nWith v1.13.14 I get a ClassCastException `Build_gradle$1$1$3$1$1 cannot be cast to groovy.lang.Closure` for the following fileUpdate:\r\n\r\n```kotlin\r\nscmVersion {\r\n    hooks {\r\n         // [..] logging and custom context calls for addCommitPattern()\r\n\r\n        preRelease {\r\n            fileUpdate {\r\n                file("src/main/resources/specs/some_api.yaml")\r\n                file("src/main/resources/specs/some_other_api.yaml")\r\n                pattern = { previousVersion, _ -> "version: \'$previousVersion\'" }\r\n                replacement = { currentVersion, _ -> "version: \'$currentVersion\'" }\r\n            }\r\n        }\r\n\r\n        pre("commit")\r\n    }\r\n}\r\n```\r\nFull stacktrace:\r\n```\r\n* Exception is:                                                                                                                                   \r\norg.gradle.api.tasks.TaskExecutionException: Execution failed for task \':release\'.                                                                \r\n        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:147)        \r\n        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)                                                                       \r\n        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:145)                 \r\n        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:133)                        \r\n        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)                       \r\n        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)                 \r\n        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)             \r\n        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)                   \r\n        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)                                 \r\n        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)                         \r\n        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)                         \r\n        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)                                \r\n        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)                                \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)  \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)  \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)                              \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)                              \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)                               \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)                                \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)                                   \r\n        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)                               \r\n        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)                               \r\n        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)                                                 \r\n        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:333)         \r\n        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:320)         \r\n        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:313)\r\n        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:299)\r\n        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:143)                                \r\n        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:227)                                     \r\n        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:218)                             \r\n        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:140)                                         \r\n        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)                                 \r\n        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)                                                  \r\nCaused by: java.lang.ClassCastException: Build_gradle$1$1$3$1$1 cannot be cast to groovy.lang.Closure                                             \r\n        at pl.allegro.tech.build.axion.release.domain.hooks.FileUpdateHookAction.updateInFile(FileUpdateHookAction.java:34)                       \r\n        at pl.allegro.tech.build.axion.release.domain.hooks.FileUpdateHookAction.lambda$act$1(FileUpdateHookAction.java:27)                       \r\n        at pl.allegro.tech.build.axion.release.domain.hooks.FileUpdateHookAction.act(FileUpdateHookAction.java:27)                                \r\n        at pl.allegro.tech.build.axion.release.domain.hooks.ReleaseHooksRunner.lambda$runPreReleaseHooks$0(ReleaseHooksRunner.java:25)            \r\n        at pl.allegro.tech.build.axion.release.domain.hooks.ReleaseHooksRunner.runPreReleaseHooks(ReleaseHooksRunner.java:25)                     \r\n        at pl.allegro.tech.build.axion.release.domain.Releaser.release(Releaser.java:34)                                                          \r\n        at pl.allegro.tech.build.axion.release.domain.Releaser.releaseAndPush(Releaser.java:49)                                                   \r\n        at pl.allegro.tech.build.axion.release.domain.Releaser$releaseAndPush.call(Unknown Source)                                                \r\n        at pl.allegro.tech.build.axion.release.ReleaseTask.release(ReleaseTask.groovy:24)                                                         \r\n        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)                                                                     \r\n        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)                                   \r\n        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)                                     \r\n        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)                                     \r\n        at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:242)                                                    \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)                              \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)                              \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)                              \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)                              \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)                               \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)                                \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)                                    \r\n        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)                                \r\n        at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:227)                                            \r\n        at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:210)                                           \r\n        at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:193)                           \r\n        at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:171)                                                  \r\n        at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:89)                                                   \r\n        at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:40)                                                        \r\n        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:53)                                                            \r\n        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:50)                                                            \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)  \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)  \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)                              \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)                              \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)                               \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)                                \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)                                   \r\n        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)                               \r\n        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:50)                                                           \r\n        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:40)                                                           \r\n        at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:68)                               \r\n        at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:38)                               \r\n        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)                                   \r\n        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:36)                                   \r\n        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41)                                           \r\n        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74)                                             \r\n        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)                                                           \r\n        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)                                               \r\n        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:29)                                               \r\n        at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:61)                     \r\n        at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:42)                     \r\n        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:60)                         \r\n        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:27)                         \r\n        at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:180)                                        \r\n        at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$1(BuildCacheStep.java:75)                                            \r\n        at org.gradle.internal.Either$Right.fold(Either.java:175)                                                                                 \r\n        at org.gradle.internal.execution.caching.CachingState.fold(CachingState.java:59)                                                          \r\n        at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:73)                                                     \r\n        at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:48)                                                     \r\n        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:36)                                   \r\n        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:25)                                   \r\n        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:36)                                               \r\n        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:22)                                               \r\n        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:110)                                         \r\n        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:56)                                        \r\n        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:56)                                                 \r\n        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)                                                 \r\n        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:73)                                             \r\n        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:44)                                             \r\n        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)      \r\n        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)      \r\n        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:89)                                   \r\n        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:50)                                   \r\n        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:114)                                                        \r\n        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:57)                                                         \r\n        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:76)                   \r\n        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:50)                   \r\n        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.executeWithNoEmptySources(SkipEmptyWorkStep.java:249)                            \r\n        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:86)                                               \r\n        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:54)                                               \r\n        at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:32)               \r\n        at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:21)               \r\n        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)        \r\n        at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:43)                     \r\n        at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:31)                     \r\n        at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:40)                                  \r\n        at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:287)                                          \r\n        at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:40)                                           \r\n        at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)                                           \r\n        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)                                               \r\n        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27)                                               \r\n        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:44)                                                         \r\n        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:33)                                                         \r\n        at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:76)                                    \r\n        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:144)                 \r\n        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:133)                        \r\n        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)                       \r\n        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)                 \r\n        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)             \r\n        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)                   \r\n        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)                                 \r\n        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)                         \r\n        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)                         \r\n        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)                                \r\n        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)                                \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)  \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)  \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)                              \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)                              \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)                               \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)                                \r\n        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)                                   \r\n        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)                               \r\n        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)                               \r\n        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)                                                 \r\n        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:333)         \r\n        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:320)         \r\n        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:313)\r\n        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:299)\r\n        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:143)                                \r\n        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:227)                                     \r\n        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:218)                             \r\n        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:140)                                         \r\n        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)                                 \r\n        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)                                                  \r\n```\r\n\r\nI\'m able to work around it using the methods described initially in #449 \r\n```kotlin\r\n  preFileUpdate(\r\n      file = src/main/resources/specs/some_api.yaml,\r\n      pattern = { previousVersion, _ -> "version: \'$previousVersion\'" },\r\n      replacement = { currentVersion, _ -> "version: \'$currentVersion\'" }\r\n  )\r\n  preFileUpdate(\r\n      file = "src/main/resources/specs/some_other_api.yaml",\r\n      pattern = { previousVersion, _ -> "version: \'$previousVersion\'" },\r\n      replacement = { currentVersion, _ -> "version: \'$currentVersion\'" }\r\n  )\r\n```',
        labels: [
            {
                id: 725512156,
                node_id: 'MDU6TGFiZWw3MjU1MTIxNTY=',
                url: 'https://api.github.com/repos/allegro/axion-release-plugin/labels/hacktoberfest',
                name: 'hacktoberfest',
                color: 'f3a9f9',
                default: false,
                description: null,
            },
            {
                id: 4605351285,
                node_id: 'LA_kwDOAW-go88AAAABEoAVdQ',
                url: 'https://api.github.com/repos/allegro/axion-release-plugin/labels/good-first-issue',
                name: 'good-first-issue',
                color: 'c2e0c6',
                default: false,
                description: '',
            },
        ],
        assignees: 0,
        comments: 4,
        created_at: '2022-06-22T18:15:53Z',
    },
    {
        issues: 'https://api.github.com/repos/endoflife-date/endoflife.date/issues/408',
        title: '\ud83d\ude80\ud83d\ude80 README for Hacktoberfest Participants \ud83d\ude80\ud83d\ude80',
        body: "Welcome to Hacktoberfest 2022! endoflife.date is a simple informational (open-source) website that details the support lifecycles of various products. If you are interesting in earning [some swag](https://hacktoberfest.digitalocean.com/resources/participation) and helping this project, read on. Please read this document completely before filing a Pull Request.\r\n\r\nBefore you get started, get to know the project a little bit. Open [endoflife.date](https://endoflife.date) and browse around a little bit. Take a look at some of these recently merged PRs to get a better idea: [#1598](https://github.com/endoflife-date/endoflife.date/pull/1598), [#1603](https://github.com/endoflife-date/endoflife.date/pull/1603), [#1552](https://github.com/endoflife-date/endoflife.date/pull/1552), [#1596](https://github.com/endoflife-date/endoflife.date/pull/1596).\r\n\r\n## About the codebase\r\n\r\nendoflife.date is built using [Jekyll](https://jekyllrb.com/) - the Ruby static site builder that powers GitHub Pages. The site is built and deployed to [Netlify](https://netlify.com). Since the site is mostly informational, you _don't need programming skills to contribute to the project_.\r\n\r\n## \ud83d\udc7e Recommended PRs and Changes\r\n\r\nHere's some recommendations for good first contributions to the codebase. We've also made sure that there are enough details on linked issues for beginners to start working on them.\r\n\r\n### \ud83c\udd95 Release Updates\r\n\r\nThe bulk majority of PRs to the project are trivial release update PRs. You can see previously merged PRs [using the `release-updates`](https://github.com/endoflife-date/endoflife.date/pulls?q=is%3Apr+sort%3Aupdated-desc+label%3Arelease-updates+is%3Aclosed) label as a guide. If a new release has been made for a project that is currently being tracked on the endoflife.date website, we welcome PRs for updating the data around for that new release. If you make such a PR, here's a short checklist to follow:\r\n\r\n- Have you updated _all of the release cycles_ that might have got an update?\r\n- Has any previous release reached end of life? Does that need updating?\r\n- If it's a new major release (which needs a new release cycle to be added), do we have a corresponding EoL dates for it?\r\n- Is the page automatically updated? If so, our automation bot might beat you to it.\r\n\r\n### \ud83d\udc85 Design and Layout Changes\r\n\r\nIf you're comfortable with SASS, Jekyll, HTML, Javascript - we're looking for some help around easy to fix design issues on the website. Make sure you've read through the [HACKING.md](https://github.com/endoflife-date/endoflife.date/blob/master/HACKING.md) file and setup the project locally before you start working on these.\r\n\r\nNote that we are looking for good clean code, and unmaintainable hacks might be rejected. Make sure your changes align with the Jekyll Philosophy (for eg using SCSS mixings and Jekyll best practices).\r\n\r\nClick through the following issues to read more.\r\n\r\n- [Autofocus to search input](https://github.com/endoflife-date/endoflife.date/issues/367)\r\n- [Hide old releases by default](https://github.com/endoflife-date/endoflife.date/issues/50)\r\n- [Add Product Logo in the sidebar](https://github.com/endoflife-date/endoflife.date/issues/283)\r\n\r\nThe following require a better understanding of Jekyll and Liquid templating. A simple easy-medium-hard rating is here to help you decide as well.:\r\n\r\n- [Update API to use ChangeLog template](https://github.com/endoflife-date/endoflife.date/issues/394) (Medium)\r\n- [Generate RSS Feed for every product](https://github.com/endoflife-date/endoflife.date/issues/48) (Hard)\r\n- [Add a Last Modified Date](https://github.com/endoflife-date/endoflife.date/issues/70) (Easy)\r\n- [Support LTS Dates](https://github.com/endoflife-date/endoflife.date/issues/156) (Medium)\r\n- [Support Dark Mode](https://github.com/just-the-docs/just-the-docs/issues/234) (Medium)\r\n\r\n### \ud83e\udd84 Adding New Products\r\n\r\nThe [Guiding Principles](https://github.com/endoflife-date/endoflife.date/wiki/Guiding-Principles) of the project state that \"it exists to be useful to the readers\". The more products we track, the more helpful we become. We're currently tracking 66 products, and we'd like to track more. Here's a list of suggested products that we think are worth tracking. File a PR for any of these! A few have links to upstream project websites to help you find the actual dates for these projects.\r\n\r\n- [Azure Kubernetes Service](https://github.com/endoflife-date/endoflife.date/issues/133)\r\n- Internet Explorer\r\n- ~~Apache Tomcat~~\r\n- iPad\r\n- ~~Samsung Galaxy Phones~~\r\n- [Plesk](https://www.plesk.com/lifecycle-policy/)\r\n- ~~Linux Mint~~\r\n- [cPanel](https://docs.cpanel.net/knowledge-base/cpanel-product/product-versions-and-the-release-process/)\r\n- ~~VMWare ESXi~~\r\n- ~~VMWare Horizon (#540)~~\r\n- ~~VMWare Citrix (#540)~~\r\n- ~~[Microsoft Exchange](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/supportability-matrix?view=exchserver-2019), [more](https://docs.microsoft.com/en-us/microsoft-365/enterprise/exchange-2010-end-of-support?view=o365-worldwide)~~\r\n- Quickbooks\r\n- Various [Forza Games](https://culturedvultures.com/forza-end-of-life-process/)\r\n- Movable Type\r\n- Apache Cassandra\r\n- Apache Mesos\r\n- Rancher\r\n- ~~Docker~~\r\n- Ceph\r\n- Postfix\r\n- Envoy\r\n- ~~HAProxy~~\r\n- ~~Apache (the webserver)~~\r\n- Many other Atlassian, Oracle, and IBM products.\r\n\r\n> (This list is based on personal observations, requests from users, google keyword research, and [this list maintained by @witchcraze](https://qiita.com/witchcraze/items/af8ac5da5948ff6a609e).\r\n\r\nIf you'd like to create a new page for something that is not on the above list - that's okay as well. We haven't had to reject a product so far, and doubt we will reject what you propose. Just make sure it is a _well known product_. We are open to accepting devices, frameworks, languages, operating-systems, applications, and pretty much everything that has a support lifecycle of some sort. If in doubt, ask us.\r\n\r\nIn creating a new page, make sure you read through [CONTRIBUTING.md](https://github.com/endoflife-date/endoflife.date/blob/master/CONTRIBUTING.md) to understand the file structure, and go through a few of previously merged PRs [with the label `new-product`](https://github.com/endoflife-date/endoflife.date/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+label%3Anew-product). Also, please read through the [Guiding Principles](https://github.com/endoflife-date/endoflife.date/wiki/Guiding-Principles) to make sure your writing style and content is good enough and matches the rest of the site. Reading these will help you get onboarded faster and make sure that your PR sees a speedy merge.\r\n\r\n### \ud83d\udcdd Changelog Links\r\n\r\nNot all of the products on the website have their latest releases linked to a relevant page. Usually this is the changelog for that release or a blog post.\r\n\r\nSee this issue for all the details: https://github.com/endoflife-date/endoflife.date/issues/39\r\n\r\n### Miscellaneous Contributions\r\n\r\nWe have issues labelled as [good first issue](https://github.com/endoflife-date/endoflife.date/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) for easy to pick up contributions. All of these have a detailed comment at the bottom telling exactly what needs to be done, and what skills might be needed.\r\n\r\nIf you'd like to suggest a new product to track, please create a new issue. Issues are also welcome if you have any suggestions for the website in general - around design, visibility, accessibility, usability for eg.\r\n\r\n## \ud83d\udc69\u200d\ud83c\udf93 How to file a Pull Request\r\n\r\nFor most trivial changes (mainly release update and small content fixes), you can make these using the GitHub UI itself - just to to the relevant file and click the Pencil icon:\r\n\r\n![image](https://user-images.githubusercontent.com/584253/134509844-197cb6fb-5d6d-4d8b-bf0b-84d6f0cf6989.png)\r\n\r\nEdit the file accordingly, then type a good title and description for your changes:\r\n\r\n![image](https://user-images.githubusercontent.com/584253/134510105-1efacea4-8044-4b24-ae83-237539442fb6.png)\r\n\r\nClick \"Propose Changes\" and then review the changes you've made before clicking \"Create Pull Request\". If you still need to make more changes, create a \"Draft Pull Request\" by clicking the dropdown on the \"Create Pull Request\" button:\r\n\r\n![](https://docs.github.com/assets/images/help/pull_requests/pullrequest-send.png).\r\n\r\nYou can change the PR from a Draft PR to a ready PR afterwards.\r\n\r\n## \u2705 Validating your changes\r\n\r\nOnce you file your Pull Request, Netlify will provide a list of checks for your changes. If one of the checks is failed, you can click Details and see through the errors, or one of the Maintainers will be there to help you soon.\r\n\r\nIf all of the checks pass, you can click the \"Details\" link on the \"Deploy Preview\" Status Check to see a preview of the website _with your changes_.\r\n\r\n![image](https://user-images.githubusercontent.com/584253/134535142-7d1170b7-16f4-4cd3-987e-e890b76098d5.png)\r\n\r\nClick through, and validate your changes. Click all the links in the page you've changed and make sure they're not broken.\r\n\r\n## \ud83d\udcd1 Suggested Reading\r\n\r\nPlease make sure that you've gone through the Hacktoberfest [Quality Standards](https://hacktoberfest.digitalocean.com/resources/qualitystandards) and the [Participation Guidelines](https://hacktoberfest.digitalocean.com/resources/participation).\r\n\r\nAdditionally, we have the following documents which should help you get familiar with the project and the codebase. You don't need to read all of these, and we've linked these docs above in cases where you must read any of them.\r\n\r\n- [HACKING.md](https://github.com/endoflife-date/endoflife.date/blob/master/HACKING.md) contains instructions on setting up the codebase locally with Jekyll. Read this if you're planning to make complex changes or setting up the project locally.\r\n- [Guiding Principles](https://github.com/endoflife-date/endoflife.date/wiki/Guiding-Principles) - These help us make decisions around the content we have. If you'd like to make sure your PR gets a speedy approval, please read these to ensure your changes are aligned with the rest of the content. This is _especially important if you are making non-trivial changes_ that deal with the content or add a new product.\r\n- [CONTRIBUTING.md](https://github.com/endoflife-date/endoflife.date/blob/master/CONTRIBUTING.md) - This walks you through the structure each product page takes, in detailed comments. Do read this if you are _adding a new product page to the website_.\r\n- [Code of Conduct](https://github.com/endoflife-date/endoflife.date/blob/master/CODE-OF-CONDUCT.md) - This project follows the Contributor Covenant Code of Conduct, which you can read at this link. You must read this and agree to abide by this at all times in your interactions with this project and its community.\r\n\r\n# \u2753 Questions?\r\n\r\nIf you have any questions, please [create a new Discussion under the Hacktoberfest category](https://github.com/endoflife-date/endoflife.date/discussions/new?category=hacktoberfest). If you are picking up a new task, first check if there is already a PR for the same, and if not - [create a Draft Pull Request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) as soon as you can so others do not pick up the same task.\r\n\r\nThis issue is pinned and locked permitted to keep this clean for Hacktoberfest related announcements. Please [create a new Discussions](https://github.com/endoflife-date/endoflife.date/discussions/new?category=hacktoberfest) in the Hacktoberfest category instead.",
        labels: [
            {
                id: 3405392125,
                node_id: 'LA_kwDOC0FNEs7K-ij9',
                url: 'https://api.github.com/repos/endoflife-date/endoflife.date/labels/Hacktoberfest',
                name: 'Hacktoberfest',
                color: '430C99',
                default: false,
                description:
                    'Issues that are good first picks for Hacktoberfest participants',
            },
            {
                id: 5080381010,
                node_id: 'LA_kwDOC0FNEs8AAAABLtB2Ug',
                url: 'https://api.github.com/repos/endoflife-date/endoflife.date/labels/good-first-issue',
                name: 'good-first-issue',
                color: 'D55ADB',
                default: false,
                description: 'Good for newcomers',
            },
        ],
        assignees: 0,
        comments: 0,
        created_at: '2021-09-23T15:59:32Z',
    },
    {
        issues: 'https://api.github.com/repos/hyperledger/cacti/issues/675',
        title: 'feat(consortium-indy): support consortium database indy backend',
        body: "**Is your feature request related to a problem? Please describe.**\n\nCurrently the only consortium plugin we have is the `manual` one which is very bare bones, basically the consortium plugin equivalent of what the in-memory keychain plugin is for keychains (e.g. it's mostly just good for writing tests without having to simulate costly additional infrastructure software for test cases).\n\n**Describe the solution you'd like**\n\nThe implementation should have the same endpoints/methods as the manual consortium plugin with the big difference being that the consortium database data is being pulled from an Indy ledger rather than from in-memory.\nThis way the consensus around who is in the consortium is outsourced to the Indy ledger (with all of it's problems which is great for us).\nEssentially the plugin is just a resolver for DIDs on Indy.\n\n**Describe alternatives you've considered**\n\nNothing, I'm pretty sure we need this.\n\n**Additional context**\n\nI put this under the epic of pluggable authentication but it's a slightly different topic (lines are blurred)\n\ncc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton @AzaharaC @jordigiam @kikoncuo @mwklein",
        labels: [
            {
                id: 1629728755,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzU1',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/enhancement',
                name: 'enhancement',
                color: 'a2eeef',
                default: true,
                description: 'New feature or request',
            },
            {
                id: 1629728757,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzU3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue',
                name: 'good-first-issue',
                color: '7057ff',
                default: false,
                description: 'Good for newcomers',
            },
            {
                id: 2411211154,
                node_id: 'MDU6TGFiZWwyNDExMjExMTU0',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Hacktoberfest',
                name: 'Hacktoberfest',
                color: '9bc6f2',
                default: false,
                description:
                    'Hacktoberfest participants are welcome to take a stab at issues marked with this label.',
            },
            {
                id: 2655484960,
                node_id: 'MDU6TGFiZWwyNjU1NDg0OTYw',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Core_API',
                name: 'Core_API',
                color: 'EB0D40',
                default: false,
                description: 'Changes related to the Core API Package',
            },
            {
                id: 2924324338,
                node_id: 'MDU6TGFiZWwyOTI0MzI0MzM4',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue-400-expert',
                name: 'good-first-issue-400-expert',
                color: 'DF3D22',
                default: false,
                description: '',
            },
            {
                id: 3515616541,
                node_id: 'LA_kwDODOk1Zs7RjA0d',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/P3',
                name: 'P3',
                color: 'FBCA04',
                default: false,
                description: 'Priority 3: Medium',
            },
        ],
        assignees: 0,
        comments: 0,
        created_at: '2021-03-16T19:41:40Z',
    },
    {
        issues: 'https://api.github.com/repos/hyperledger/cacti/issues/393',
        title: 'build(api-client): generate java, go clients',
        body: "### Description\r\n\r\nAs a developer I want to not be forced to use the NodeJS/Javascript API client if my primary programming language is something else so that I can achieve high productivity through Cactus no matter the language I'm using.\r\n\r\n- This is different from a similar looking issue which discusses the possibility of writing plugins in different languages as well.\r\n- We do not need write much Go/Java code because 99% of it is auto-generated. See the Acceptance criteria 4)\r\n\r\nHere is a complete list of programming languages that are supported by the OpenAPI generator (which we can take full advantage of since we are using the OpenAPI specs)\r\nhttps://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages\r\n\r\n### Acceptance Criteria\r\n1. Clients for Java and Go are generated as part of the full build\r\n2. Dev builds only build the Typescript API client to remain as fast as possible\r\n3. Publishing of the Java and Go API clients is included in the release process => if I run the release scripts the full build runs and the Java, Go clients are published/made available for public consumption the same way we do with the Typescript API client (it gets published to npm)\r\n4. Client side routing is supported by the Go/Java API clients as well.\r\n\r\ncc: @takeutak @sfuji822 @jonathan-m-hamilton \r\n",
        labels: [
            {
                id: 1629728755,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzU1',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/enhancement',
                name: 'enhancement',
                color: 'a2eeef',
                default: true,
                description: 'New feature or request',
            },
            {
                id: 1629728757,
                node_id: 'MDU6TGFiZWwxNjI5NzI4NzU3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/good-first-issue',
                name: 'good-first-issue',
                color: '7057ff',
                default: false,
                description: 'Good for newcomers',
            },
            {
                id: 1657071350,
                node_id: 'MDU6TGFiZWwxNjU3MDcxMzUw',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Nice-to-Have',
                name: 'Nice-to-Have',
                color: '5ea0bc',
                default: false,
                description: '',
            },
            {
                id: 1762140891,
                node_id: 'MDU6TGFiZWwxNzYyMTQwODkx',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/dependencies',
                name: 'dependencies',
                color: '0366d6',
                default: false,
                description: 'Pull requests that update a dependency file',
            },
            {
                id: 2092205837,
                node_id: 'MDU6TGFiZWwyMDkyMjA1ODM3',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Developer_Experience',
                name: 'Developer_Experience',
                color: '5319e7',
                default: false,
                description: '',
            },
            {
                id: 2411211154,
                node_id: 'MDU6TGFiZWwyNDExMjExMTU0',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/Hacktoberfest',
                name: 'Hacktoberfest',
                color: '9bc6f2',
                default: false,
                description:
                    'Hacktoberfest participants are welcome to take a stab at issues marked with this label.',
            },
            {
                id: 3515615640,
                node_id: 'LA_kwDODOk1Zs7RjAmY',
                url: 'https://api.github.com/repos/hyperledger/cacti/labels/P1',
                name: 'P1',
                color: 'B60205',
                default: false,
                description: 'Priority 1: Highest',
            },
        ],
        assignees: 1,
        comments: 4,
        created_at: '2020-11-20T00:08:01Z',
    },
];
